project:
  type: book
  output-dir: docs

language: _ua.yml
# crossref: 
#   title-delim: "&nbsp;-&nbsp;"
code-annotations: below

# filters:
#   - first-line-indent

profile:
  default: development

book:
  title: "Прикладний статистичний аналіз"
  subtitle: "Посібник для студентів"
  reader-mode: true

  page-footer:
    left: |
      Прикладний статистичний аналіз
    right: |
      Ця книга створена за допомогою <a href="https://quarto.org/">Quarto</a>.

  author: 
    - name: Ігор Мірошниченко
      orcid: 0000-0002-1307-7889
      email: ihor.miroshnychenko@knu.ua
      affiliation: 
        - name: "Київський національний університет імені Тараса Шевченка"
          department: "Кафедра технологій управління"
    - name: Юлія Хлевна
      orcid: 0000-0002-1874-1961
      email: yuliia.khlevna@knu.ua
      affiliation:
        - name: "Київський національний університет імені Тараса Шевченка"
          department: "Кафедра технологій управління"
  date: today
  date-format: iso

  chapters:
    - index.qmd
    - intro.qmd
    - binom.qmd
    - power.qmd
    - z-test.qmd
    - t-test.qmd
    - monte-carlo.qmd
    # - kolmogorov.qmd
    # - chi-sq.qmd
    # - mann-whitney.qmd
    # - bootstrap.qmd
    # - summary.qmd
    - references.qmd

bibliography: references.bib
bibliographystyle: apa
nocite: |
  @*

format:
  html:
    theme: 
      light: [cosmo, ims-style.scss]
      dark: [cosmo, ims-style-dark.scss]
    code-link: true
  docx:
    reference-doc: word-template.docx
  pdf:
  #  indent: true
  #  first-line-indent:
  #    size: 1.25cm
   sansfont: Calibri
   mainfont: Georgia
   monofont: Consolas
   include-in-header: latex/as-style.tex
   geometry:
    - top=25mm
    - left=18mm
    - right=18mm
    - bottom=20mm
    - heightrounded
   colorlinks: true
   documentclass: report
   classoption: 
     - 10pt
     - openany
   pdf-engine: xelatex
   biblio-style: apalike
   keep-tex: false
   block-headings: false
  #  top-level-division: chapter
   fig-dpi: 300
   fig-show: hold
   fig-pos: H
   tbl-pos: H
   fig-align: center
   toc: true
   toc-depth: 3

