project:
  type: book
  output-dir: docs

language: _ua.yml
# crossref: 
#   title-delim: "&nbsp;-&nbsp;"

profile:
  default: development

book:
  title: "Прикладний статистичний аналіз"
  reader-mode: true


  page-footer:
    left: |
      Прикладний статистичний аналіз
    right: |
      Ця книга створена за допомогою <a href="https://quarto.org/">Quarto</a>.

  author: 
    - name: Ігор Мірошниченко
      orcid: 0000-0002-1307-7889
      email: ihor.miroshnychenko@knu.ua
      affiliation: "Київський національний університет імені Тараса Шевченка"
    - name: Юлія Хлевна
      orcid: 0000-0002-1874-1961
      email: yuliia.khlevna@knu.ua
      affiliation: "Київський національний університет імені Тараса Шевченка"
  date: today
  date-format: iso

  chapters:
    - index.qmd
    - intro.qmd
    - binom.qmd
    - z-test.qmd
    - t-test.qmd
    - monte-carlo.qmd
    - kolmogorov.qmd
    - chi-sq.qmd
    - mann-whitney.qmd
    - bootstrap.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: [cosmo, ims-style.scss]
    code-link: true
  docx:
    reference-doc: word-template.docx
  # pdf:
  #  include-in-header: latex/ims-style.tex
  #  include-after-body: latex/after-body.tex
  #  documentclass: book
  #  classoption: 
  #    - 10pt
  #    - openany
  #  pdf-engine: xelatex
  #  biblio-style: apalike
  #  keep-tex: true
  #  block-headings: false
  #  top-level-division: chapter
  #  fig-dpi: 300
  #  fig-show: hold
  #  fig-pos: H
  #  tbl-pos: H
  #  fig-align: center
  #  toc: true
  #  toc-depth: 2

