<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.6.42">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>4&nbsp; t-критерій Стьюдента – Прикладний статистичний аналіз</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
  margin-bottom: 0em;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./monte-carlo.html" rel="next">
<link href="./z-test.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-2f5df379a58b258e96c21c0638c20c03.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-6c380caa1d326ca7d97976c903cdd929.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "Не має результатів",
    "search-matching-documents-text": "Результати пошуку",
    "search-copy-link-title": "Скопіювати посилання",
    "search-hide-matches-text": "Сховати додаткові результати",
    "search-more-match-text": "додатковий результат у цьому документі",
    "search-more-matches-text": "додаткових результатів у цьому документі",
    "search-clear-button-title": "Очистити",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Відмінити",
    "search-submit-button-title": "Надіслати",
    "search-label": "Пошук"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="nav-sidebar floating">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Переключити бокову панель навігації" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./t-test.html"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title"><span class="math inline">\(t\)</span>-критерій Стьюдента</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Переключити бокову панель навігації" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Пошук" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Прикладний статистичний аналіз</a> 
        <div class="sidebar-tools-main">
  <a href="" class="quarto-reader-toggle quarto-navigation-tool px-1" onclick="window.quartoToggleReader(); return false;" title="Переключити режим читання">
  <div class="quarto-reader-toggle-btn">
  <i class="bi"></i>
  </div>
</a>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Пошук"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Передмова</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./intro.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Вступ</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./binom.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Біноміальний критерій</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./power.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Статистична потужність, ефект та довірчі інтервали</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./z-test.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title"><span class="math inline">\(Z\)</span>-критерій Фішера</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./t-test.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title"><span class="math inline">\(t\)</span>-критерій Стьюдента</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./monte-carlo.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Монте-Карло в задачах статистики</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./summary.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Підсумки</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./references.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Список літератури</span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Зміст</h2>
   
  <ul>
  <li><a href="#основні-положення" id="toc-основні-положення" class="nav-link active" data-scroll-target="#основні-положення"><span class="header-section-number">4.1</span> Основні положення</a></li>
  <li><a href="#t-тест-стьюдента" id="toc-t-тест-стьюдента" class="nav-link" data-scroll-target="#t-тест-стьюдента"><span class="header-section-number">4.2</span> <span class="math inline">\(t\)</span>-тест Стьюдента</a></li>
  <li><a href="#t-тест-у-python" id="toc-t-тест-у-python" class="nav-link" data-scroll-target="#t-тест-у-python"><span class="header-section-number">4.3</span> <span class="math inline">\(t\)</span>-тест у Python</a></li>
  <li><a href="#довірчі-інтервали" id="toc-довірчі-інтервали" class="nav-link" data-scroll-target="#довірчі-інтервали"><span class="header-section-number">4.4</span> Довірчі інтервали</a>
  <ul class="collapse">
  <li><a href="#перший-метод" id="toc-перший-метод" class="nav-link" data-scroll-target="#перший-метод"><span class="header-section-number">4.4.1</span> Перший метод</a></li>
  <li><a href="#другий-метод" id="toc-другий-метод" class="nav-link" data-scroll-target="#другий-метод"><span class="header-section-number">4.4.2</span> Другий метод</a></li>
  </ul></li>
  <li><a href="#довірчі-інтервали-у-python" id="toc-довірчі-інтервали-у-python" class="nav-link" data-scroll-target="#довірчі-інтервали-у-python"><span class="header-section-number">4.5</span> Довірчі інтервали у Python</a></li>
  <li><a href="#t-тест-та-вимога-нормальності" id="toc-t-тест-та-вимога-нормальності" class="nav-link" data-scroll-target="#t-тест-та-вимога-нормальності"><span class="header-section-number">4.6</span> <span class="math inline">\(t\)</span>-тест та вимога нормальності</a>
  <ul class="collapse">
  <li><a href="#t-тест" id="toc-t-тест" class="nav-link" data-scroll-target="#t-тест"><span class="header-section-number">4.6.1</span> <span class="math inline">\(t'\)</span>-тест</a></li>
  </ul></li>
  <li><a href="#довірчий-інтервал" id="toc-довірчий-інтервал" class="nav-link" data-scroll-target="#довірчий-інтервал"><span class="header-section-number">4.7</span> Довірчий інтервал</a></li>
  <li><a href="#вибір-критерію" id="toc-вибір-критерію" class="nav-link" data-scroll-target="#вибір-критерію"><span class="header-section-number">4.8</span> Вибір критерію</a></li>
  <li><a href="#мінімальний-ефект" id="toc-мінімальний-ефект" class="nav-link" data-scroll-target="#мінімальний-ефект"><span class="header-section-number">4.9</span> Мінімальний ефект</a></li>
  <li><a href="#двовибірковий-t-тест" id="toc-двовибірковий-t-тест" class="nav-link" data-scroll-target="#двовибірковий-t-тест"><span class="header-section-number">4.10</span> Двовибірковий <span class="math inline">\(t\)</span>-тест</a>
  <ul class="collapse">
  <li><a href="#двовибірковий-t-тест-у-python" id="toc-двовибірковий-t-тест-у-python" class="nav-link" data-scroll-target="#двовибірковий-t-тест-у-python"><span class="header-section-number">4.10.1</span> Двовибірковий <span class="math inline">\(t\)</span>-тест у Python</a></li>
  </ul></li>
  <li><a href="#контрольні-питання" id="toc-контрольні-питання" class="nav-link" data-scroll-target="#контрольні-питання"><span class="header-section-number">4.11</span> Контрольні питання</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title"><span id="sec-t-test" class="quarto-section-identifier"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title"><span class="math inline">\(t\)</span>-критерій Стьюдента</span></span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<section id="основні-положення" class="level2" data-number="4.1">
<h2 data-number="4.1" class="anchored" data-anchor-id="основні-положення"><span class="header-section-number">4.1</span> Основні положення</h2>
<p>Спробуємо розв’язати таке завдання.</p>
<div id="exm-task" class="theorem example">
<p><span class="theorem-title"><strong>Приклад 4.1</strong></span> &nbsp;</p>
<blockquote class="blockquote">
<p>Менеджмент компанії розглядає новий підхід до планування щотижневих нарад, щоб зменшити втрати часу співробітників. Раніше середня тривалість таких нарад складала 70 хвилин. Ідея полягає в тому, щоб перейти до нової структури нарад, яка, за задумом, дозволить зменшити тривалість нарад до 60 хвилин.</p>
</blockquote>
<blockquote class="blockquote">
<p>Протягом одного тижня провели 7 нарад у новому форматі й зафіксували їх тривалість. Якщо з’ясується, що нові наради тривають довше, ніж у середньому 70 хвилин, новий формат вважатимуть неефективним.</p>
</blockquote>
<blockquote class="blockquote">
<p>Ваше завдання — перевірити, чи новий формат нарад дійсно ефективніший.</p>
</blockquote>
<blockquote class="blockquote">
<p>Вийшла вибірка середньої тривалості нарад (в хвилинах): <code>[50, 55, 70, 45, 40, 70, 80]</code>.</p>
</blockquote>
</div>
<p>Для початку переформулюємо умову мовою математики. Є вибірка:</p>
<ul>
<li><span class="math inline">\(X_1, X_2, ..., X_7\)</span> — значення середньої тривалості нарад у новому форматі;</li>
<li>Будемо вважати, що <span class="math inline">\(X\)</span> з нормального розподілу, тобто <span class="math inline">\(X \sim N(\mu, \sigma^2)\)</span>.</li>
</ul>
<div id="a6a980cc" class="cell" data-execution_count="2">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>meeting_time <span class="op">=</span> np.array([<span class="dv">50</span>, <span class="dv">55</span>, <span class="dv">70</span>, <span class="dv">45</span>, <span class="dv">40</span>, <span class="dv">70</span>, <span class="dv">80</span>])</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Середнє значення: </span><span class="sc">{</span>np<span class="sc">.</span>mean(meeting_time)<span class="sc">:.2f}</span><span class="ss"> хвилин"</span>)</span></code><button title="Скопіювати в буфер обміну" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Середнє значення: 58.57 хвилин</code></pre>
</div>
</div>
<p>Наша гіпотеза звучить так:</p>
<p><span class="math display">\[
H_0: E \overline{X} \geq 70 \; \text{проти} \; H_1: E \overline{X} &lt; 70
\]</span></p>
<p>Здається, що ми таке вже вміємо вирішувати: згадаємо про <span class="math inline">\(Z\)</span>-критерій:</p>
<p><span class="math display">\[
H_0: \mu \leq \mu_0\ \; \text{проти} \; \ H_1: \mu &gt; \mu_0
\]</span></p>
<ul>
<li>Статистика <span class="math inline">\(Z(X) = \sqrt{n}\dfrac{\overline X - \mu_0}{\sqrt{\sigma^2}}\)</span></li>
<li>За досить великого розміру вибірки <span class="math inline">\(Z(X) \overset{H_0}{\sim} \mathcal{N}(0, 1)\)</span> (за ЦГТ)</li>
<li>Односторонній критерій: <span class="math inline">\(\left\{Z(X) \geq z_{1 - \alpha} \right\}\)</span>
<ul>
<li><span class="math inline">\(p\)</span>-значення = <span class="math inline">\(1 - \Phi(z)\)</span>, де <span class="math inline">\(z\)</span> — реалізація статистики <span class="math inline">\(Z(X)\)</span>, <span class="math inline">\(\Phi(z)\)</span> — функція розподілу <span class="math inline">\(\mathcal{N}(0, 1)\)</span></li>
</ul></li>
<li>Двосторонній критерій: <span class="math inline">\(\left\{Z(X) \geq z_{1 - \frac{\alpha}{2}} \right\} \bigcup \left\{Z(X) \leq -z_{1 - \frac{\alpha}{2}} \right\}\)</span>
<ul>
<li><span class="math inline">\(p\)</span>-значення = <span class="math inline">\(2\cdot \min \left[{\Phi(z), 1 - \Phi(z)} \right]\)</span>, де <span class="math inline">\(z\)</span> — реалізація статистики <span class="math inline">\(Z(X)\)</span></li>
</ul></li>
</ul>
<p>Тоді треба лише порахувати таку статистику: <span class="math inline">\(\sqrt{n}\dfrac{\overline X - 70}{\sqrt{\sigma^2}} \overset{H_0}{\sim} \mathcal{N}(0, 1)\)</span>.</p>
<p>Але є суттєва проблема: <strong>ми не знаємо <span class="math inline">\(\sigma^2\)</span></strong>! Тому ми не можемо використовувати <span class="math inline">\(Z\)</span>-критерій.</p>
<p>Давайте спробуємо оцінити <span class="math inline">\(\sigma^2\)</span> за допомогою вибірки. Для цього скористаємося формулою:</p>
<p><span id="eq-sample-variance"><span class="math display">\[
\hat{\sigma}^2 = S^2 = \dfrac{1}{n - 1} \sum_{i=1}^n (X_i - \overline X)^2
\tag{4.1}\]</span></span></p>
<p>Вона називається <strong>вибірковою дисперсією</strong>. Вибіркова дисперсія є <em>незміщеною</em> та <em>консистентною</em> оцінкою дисперсії генеральної сукупності.</p>
<p>Вибіркова дисперсія є <strong>незміщеною</strong>, оскільки ми ділимо на <span class="math inline">\(n - 1\)</span>, а не на <span class="math inline">\(n\)</span>. Це робиться для того, щоб уникнути систематичної помилки в оцінці дисперсії. <strong>Консистентність</strong> пояснюється тим, що з ростом вибірки <span class="math inline">\(n\)</span> ми все ближче підходимо до істинної дисперсії генеральної сукупності.</p>
<p>Для розрахунку вибіркової дисперсії в Python можна скористатися функцією <code>np.var</code> з параметром <code>ddof=1</code>, що означає, що ми ділимо на <span class="math inline">\(n - 1\)</span>.</p>
<div id="849c3679" class="cell" data-execution_count="3">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>meeting_time_var <span class="op">=</span> np.var(meeting_time, ddof<span class="op">=</span><span class="dv">1</span>)</span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Вибіркова дисперсія: </span><span class="sc">{</span>meeting_time_var<span class="sc">:.2f}</span><span class="ss"> хвилин"</span>)</span></code><button title="Скопіювати в буфер обміну" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Вибіркова дисперсія: 222.62 хвилин</code></pre>
</div>
</div>
<p>Давайте введемо новий критерій <span class="math inline">\(t'\)</span>-тест, у якому ми підставимо:</p>
<ul>
<li><span class="math inline">\(t(X) := \sqrt{n}\dfrac{\overline X - \mu_0}{\sqrt{S^2}}\)</span></li>
<li><span class="math inline">\(t(X) \overset{H_0}{\sim} \mathcal{N}(0, 1)\)</span></li>
</ul>
<p>Залишилося перевірити: <strong>Чи правда, що при <span class="math inline">\(H_0\)</span> розподіл <span class="math inline">\(t\)</span>-статистики — стандартний нормальний?</strong></p>
<p>Для цього пропонується подивитися, як насправді буде розподілена статистика <span class="math inline">\(t(X) = \sqrt{n}\dfrac{\overline{X}-\mu_0}{\sqrt{S^2}}\)</span> у завданні, яке було поставлено від початку.</p>
<p>Для цього будемо вважати, що вибірка <span class="math inline">\(X\)</span> складається з 7 елементів й <span class="math inline">\(X \sim \mathcal{N}\)</span>.</p>
<ul>
<li>Ми <span class="math inline">\(M\)</span> раз згенеруємо вибірку <span class="math inline">\(X\)</span> та порахуємо щоразу статистику <span class="math inline">\(t(X)\)</span>.</li>
<li>У підсумку ми отримаємо вибірку розміру <span class="math inline">\(M\)</span> для <span class="math inline">\(t(X)\)</span> й зможемо побудувати гістограму розподілу. Окремо побудуємо розподіл <span class="math inline">\(\mathcal{N}(0, 1)\)</span>. Якщо емпіричний розподіл візуально збіжиться з теоретичним нормальним, значить, усе добре. А якщо ні, то так просто ми не можемо замінити <span class="math inline">\(\sigma^2\)</span> на <span class="math inline">\(S^2\)</span>.
<ul>
<li>Додатково подивимося, що буде, якщо замінити <span class="math inline">\(t(X)\)</span> на <span class="math inline">\(Z(X)\)</span>. Добре, що на штучному прикладі ми знаємо дисперсію.</li>
</ul></li>
</ul>
<p>Для цього ми напишемо функцію <code>sample_statistics</code>, яка зможе побудувати розподіл для будь-якої статистики, а не тільки для <span class="math inline">\(t(X), Z(X)\)</span>. Вона приймає на вхід:</p>
<ul>
<li><code>number_of_experiments</code> — кількість експериментів, які ми хочемо провести;</li>
<li><code>statistic_function</code> — функція, яка обчислює статистику;</li>
<li><code>sample_size</code> — розмір вибірки;</li>
<li><code>sample_distr</code> — розподіл, з якого ми генеруємо вибірку.</li>
</ul>
<div id="07c14400" class="cell" data-execution_count="4">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> sample_statistics(number_of_experiments, statistic_function, sample_size, sample_distr):</span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>    statistic_sample <span class="op">=</span> []</span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a>    <span class="cf">for</span> _ <span class="kw">in</span> <span class="bu">range</span>(number_of_experiments):</span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a>        sample <span class="op">=</span> sample_distr.rvs(sample_size)</span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a>        statistic <span class="op">=</span> statistic_function(sample)</span>
<span id="cb5-6"><a href="#cb5-6" aria-hidden="true" tabindex="-1"></a>        statistic_sample.append(statistic)</span>
<span id="cb5-7"><a href="#cb5-7" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> statistic_sample</span></code><button title="Скопіювати в буфер обміну" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Тепер перевіримо, чи дійсно <span class="math inline">\(t(X)\)</span> розподілена нормально. Для цього скористаємося функцією <code>sample_statistics</code> та побудуємо гістограму для <span class="math inline">\(t(X)\)</span>. Генерувати вибірку будемо з нормального розподілу <span class="math inline">\(\mathcal{N}(5, 3^2)\)</span>.</p>
<div id="cell-fig-t-test" class="cell" data-execution_count="5">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a>sample_size <span class="op">=</span> <span class="dv">7</span></span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>M <span class="op">=</span> <span class="dv">100000</span></span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a>sample_distr <span class="op">=</span> norm(loc<span class="op">=</span><span class="dv">5</span>, scale<span class="op">=</span><span class="dv">3</span>)</span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-5"><a href="#cb6-5" aria-hidden="true" tabindex="-1"></a>T_X <span class="op">=</span> <span class="kw">lambda</span> sample: np.sqrt(sample_size) <span class="op">*</span> (np.mean(sample) <span class="op">-</span> sample_distr.mean()) <span class="op">/</span> np.sqrt(np.var(sample, ddof<span class="op">=</span><span class="dv">1</span>))</span>
<span id="cb6-6"><a href="#cb6-6" aria-hidden="true" tabindex="-1"></a>Z_X <span class="op">=</span> <span class="kw">lambda</span> sample: np.sqrt(sample_size) <span class="op">*</span> (np.mean(sample) <span class="op">-</span> sample_distr.mean()) <span class="op">/</span> sample_distr.std()</span>
<span id="cb6-7"><a href="#cb6-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-8"><a href="#cb6-8" aria-hidden="true" tabindex="-1"></a>samples <span class="op">=</span> {</span>
<span id="cb6-9"><a href="#cb6-9" aria-hidden="true" tabindex="-1"></a>    <span class="st">"T(X)"</span>: sample_statistics(</span>
<span id="cb6-10"><a href="#cb6-10" aria-hidden="true" tabindex="-1"></a>    number_of_experiments<span class="op">=</span>M, statistic_function<span class="op">=</span>T_X,</span>
<span id="cb6-11"><a href="#cb6-11" aria-hidden="true" tabindex="-1"></a>    sample_size<span class="op">=</span>sample_size, sample_distr<span class="op">=</span>sample_distr),</span>
<span id="cb6-12"><a href="#cb6-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-13"><a href="#cb6-13" aria-hidden="true" tabindex="-1"></a>    <span class="st">"Z(X)"</span>: sample_statistics(</span>
<span id="cb6-14"><a href="#cb6-14" aria-hidden="true" tabindex="-1"></a>    number_of_experiments<span class="op">=</span>M, statistic_function<span class="op">=</span>Z_X,</span>
<span id="cb6-15"><a href="#cb6-15" aria-hidden="true" tabindex="-1"></a>    sample_size<span class="op">=</span>sample_size, sample_distr<span class="op">=</span>sample_distr)</span>
<span id="cb6-16"><a href="#cb6-16" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb6-17"><a href="#cb6-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-18"><a href="#cb6-18" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> i, name <span class="kw">in</span> <span class="bu">enumerate</span>([<span class="st">"T(X)"</span>, <span class="st">"Z(X)"</span>]):</span>
<span id="cb6-19"><a href="#cb6-19" aria-hidden="true" tabindex="-1"></a>    plt.subplot(<span class="dv">1</span>, <span class="dv">2</span>, i <span class="op">+</span> <span class="dv">1</span>)</span>
<span id="cb6-20"><a href="#cb6-20" aria-hidden="true" tabindex="-1"></a>    current_sample <span class="op">=</span> samples[name]</span>
<span id="cb6-21"><a href="#cb6-21" aria-hidden="true" tabindex="-1"></a>    l_bound, r_bound <span class="op">=</span> np.quantile(current_sample, [<span class="fl">0.001</span>, <span class="fl">0.999</span>])</span>
<span id="cb6-22"><a href="#cb6-22" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-23"><a href="#cb6-23" aria-hidden="true" tabindex="-1"></a>    x <span class="op">=</span> np.linspace(l_bound, r_bound, <span class="dv">1000</span>)</span>
<span id="cb6-24"><a href="#cb6-24" aria-hidden="true" tabindex="-1"></a>    sns.distplot(current_sample, label<span class="op">=</span><span class="st">'Емпіричний розподіл'</span>, color<span class="op">=</span>turquoise)</span>
<span id="cb6-25"><a href="#cb6-25" aria-hidden="true" tabindex="-1"></a>    plt.plot(x, norm(<span class="dv">0</span>, <span class="dv">1</span>).pdf(x), label<span class="op">=</span><span class="st">'$\mathcal</span><span class="sc">{N}</span><span class="st">(0, 1)$'</span>, color<span class="op">=</span>red_pink)</span>
<span id="cb6-26"><a href="#cb6-26" aria-hidden="true" tabindex="-1"></a>    plt.legend(loc<span class="op">=</span><span class="st">'upper left'</span>)</span>
<span id="cb6-27"><a href="#cb6-27" aria-hidden="true" tabindex="-1"></a>    plt.xlabel(<span class="ss">f'</span><span class="sc">{</span>name<span class="sc">}</span><span class="ss">'</span>)</span>
<span id="cb6-28"><a href="#cb6-28" aria-hidden="true" tabindex="-1"></a>    plt.xlim((l_bound, r_bound))</span>
<span id="cb6-29"><a href="#cb6-29" aria-hidden="true" tabindex="-1"></a>    plt.ylabel(<span class="st">'Щільність'</span>)</span>
<span id="cb6-30"><a href="#cb6-30" aria-hidden="true" tabindex="-1"></a>    plt.grid(linewidth<span class="op">=</span><span class="fl">0.2</span>)</span>
<span id="cb6-31"><a href="#cb6-31" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-32"><a href="#cb6-32" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code><button title="Скопіювати в буфер обміну" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<div id="fig-t-test" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-t-test-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="t-test_files/figure-html/fig-t-test-output-1.png" width="672" height="324" class="figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-t-test-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Рисунок&nbsp;4.1: Симуляція розподілу <span class="math inline">\(t(X)\)</span> та <span class="math inline">\(Z(X)\)</span>
</figcaption>
</figure>
</div>
</div>
</div>
<p>Ми бачимо, що:</p>
<ul>
<li><span class="math inline">\(Z\)</span>-тест тут працює: <span class="math inline">\(\sqrt{n}\dfrac{\overline X - \mu_0}{\sqrt{\sigma^2}} \sim \mathcal{N}(0, 1)\)</span>.</li>
<li>Але ось для <span class="math inline">\(t(X)\)</span> це не так! **Вони відрізняються! А значить <span class="math inline">\(t'\)</span>-критерій не підходить для початкової задачі!</li>
</ul>
<p>Для того щоб стало зрозуміло, чому так сталося, розглянемо <span class="math inline">\(t(X)\)</span> у деталях. При створенні критерію є два кроки:</p>
<ol type="1">
<li>Придумати статистику для критерію
<ul>
<li>Із цим ми успішно впоралися, придумавши <span class="math inline">\(t(X)\)</span>.</li>
</ul></li>
<li>Зрозуміти розподіл статистики.
<ul>
<li>І ось це найскладніший крок, який не дозволяє використовувати будь-яку придуману статистику. Потрібно також розуміти її розподіл.</li>
<li>І з цим, як ми побачили, ми провалилися для <span class="math inline">\(t(X)\)</span>. Нормальний розподіл не підійшов.</li>
</ul></li>
</ol>
<p>Але чому <span class="math inline">\(t(X) = \sqrt{n}\dfrac{\overline X - \mu}{\sqrt{S^2}}\)</span> не розподілена нормально, хоча <span class="math inline">\(\sqrt{n}\dfrac{\overline X - \mu}{\sqrt{\sigma^2}} \overset{H_0}{\sim} \mathcal{N}(0, 1)\)</span>$? Чому при заміні <span class="math inline">\(\sigma^2\)</span> на <span class="math inline">\(S^2\)</span> усе зіпсувалося?</p>
<p><strong>Справа в тому, що <span class="math inline">\(S^2\)</span> — це випадкова величина!</strong> Згадаймо, як ми виводили <span class="math inline">\(Z\)</span>-критерій:</p>
<ol type="1">
<li>Ми порахували, що <span class="math inline">\(\overline X \sim \mathcal{N}(\mu, \sigma^2)\)</span>. З ЦГТ або, у випадку вище, з властивостей нормального розподілу.</li>
<li>Далі, все також із властивостей цього розподілу випливає, що якщо ми віднімемо константу або поділимо на константу, то нормальний розподіл не перетвориться на інший: тому <span class="math inline">\(\sqrt{n}\dfrac{\overline X - \mu_0}{\sqrt{\sigma^2}} \sim \mathcal{N}(0, 1)\)</span>.</li>
</ol>
<p><strong>Але ми нічого не знаємо про</strong> <span class="math inline">\(\dfrac{\overline{X}}{\sqrt{\eta}}\)</span>, де <span class="math inline">\(\overline{X} \sim \mathcal{N}, S^2 := \eta \sim P\)</span>, де <span class="math inline">\(P\)</span> невідомо. Ми не знаємо поки що жодних теорем, які б хоч якось доводили, що тут також залишиться нормальний розподіл.</p>
<p>Давайте подивимося на розподіл <span class="math inline">\(\sqrt{S^2}\)</span> на все тому ж нормальному розподілі.</p>
<div id="cell-fig-sample-variance" class="cell" data-execution_count="6">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>S2 <span class="op">=</span> <span class="kw">lambda</span> sample: np.std(sample, ddof<span class="op">=</span><span class="dv">1</span>)</span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>S2_sample <span class="op">=</span> sample_statistics(</span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a>    number_of_experiments<span class="op">=</span>M, statistic_function<span class="op">=</span>S2,</span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a>    sample_size<span class="op">=</span>sample_size, sample_distr<span class="op">=</span>sample_distr</span>
<span id="cb7-5"><a href="#cb7-5" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb7-6"><a href="#cb7-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-7"><a href="#cb7-7" aria-hidden="true" tabindex="-1"></a>sns.distplot(S2_sample, label<span class="op">=</span><span class="st">'Емпіричний розподіл'</span>, color<span class="op">=</span>turquoise)</span>
<span id="cb7-8"><a href="#cb7-8" aria-hidden="true" tabindex="-1"></a>plt.legend()</span>
<span id="cb7-9"><a href="#cb7-9" aria-hidden="true" tabindex="-1"></a>plt.xlabel(<span class="st">'$\sqrt{S^2}$'</span>)</span>
<span id="cb7-10"><a href="#cb7-10" aria-hidden="true" tabindex="-1"></a>plt.ylabel(<span class="st">'Щільність'</span>)</span>
<span id="cb7-11"><a href="#cb7-11" aria-hidden="true" tabindex="-1"></a>plt.grid(linewidth<span class="op">=</span><span class="fl">0.2</span>)</span>
<span id="cb7-12"><a href="#cb7-12" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code><button title="Скопіювати в буфер обміну" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<div id="fig-sample-variance" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-sample-variance-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="t-test_files/figure-html/fig-sample-variance-output-1.png" width="666" height="332" class="figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-sample-variance-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Рисунок&nbsp;4.2: Розподіл <span class="math inline">\(\sqrt{S^2}\)</span>
</figcaption>
</figure>
</div>
</div>
</div>
<p>Розподіл <span class="math inline">\(\sqrt{S^2}\)</span> несиметричний й незрозуміло як розподілений. Тому, коли ми якусь величину з нормального розподілу ділимо на несиметричний незрозумілий розподіл, ми й отримуємо, що наша статистика <span class="math inline">\(t\)</span> не з нормального розподілу.</p>
<p>Тож давайте виведемо критерій, який допоможе розв’язати початкову задачу!</p>
</section>
<section id="t-тест-стьюдента" class="level2" data-number="4.2">
<h2 data-number="4.2" class="anchored" data-anchor-id="t-тест-стьюдента"><span class="header-section-number">4.2</span> <span class="math inline">\(t\)</span>-тест Стьюдента</h2>
<p>Для того щоб вивести <span class="math inline">\(t\)</span>-тест, нам потрібно зрозуміти, як розподіляється статистика <span class="math inline">\(t(X) = \sqrt{n}\dfrac{\overline X - \mu_0}{\sqrt{S^2}}\)</span>. Для того, щоб це дізнатися, нам знадобиться кілька фактів:</p>
<ol type="1">
<li>Нехай <span class="math inline">\(X_1 \ldots X_n \sim \mathcal{N}(\mu, \sigma^2)\)</span></li>
<li>Нехай <span class="math inline">\(\xi_1 \ldots \xi_n \sim \mathcal{N}(0, 1)\)</span>. Тоді <span class="math inline">\(\eta=\xi_1^2 +\ ... +\xi_n^2 \sim \chi^2_n\)</span><a href="#fn1" class="footnote-ref" id="fnref1" role="doc-noteref"><sup>1</sup></a>.
<ul>
<li><p>Тоді <span class="math inline">\(\underset{i=1}{\overset{n}{\sum}}\left(\xi_i - \overline \xi \right)^2 \sim \chi^2_{n-1}\)</span> <a href="#fn2" class="footnote-ref" id="fnref2" role="doc-noteref"><sup>2</sup></a>.</p></li>
<li><p><span class="math inline">\(S^2_X = \dfrac{1}{n - 1}\underset{i=1}{\overset{n}{\sum}}(X_i - \overline X)^2\)</span></p></li>
<li><p><span class="math inline">\(\xi_i := \dfrac{X_i - \mu}{\sigma} \sim \mathcal{N}(0, 1)\)</span>. Тоді <span class="math display">\[\begin{aligned}
S^2_{\xi} &amp;= \dfrac{1}{n - 1}\underset{i=1}{\overset{n}{\sum}}\left(\xi_i - \overline \xi \right)^2 =
      \dfrac{1}{n - 1}\underset{i=1}{\overset{n}{\sum}} \left(\dfrac{X_i-\mu}{\sigma} - \underset{i=1}{\overset{n}{\sum}}\left[\dfrac{X_i-\mu}{n\sigma}\right] \right)^2 = \\
       &amp;= \dfrac{1}{n - 1}\underset{i=1}{\overset{n}{\sum}} \left(\dfrac{X_i}{\sigma} - \dfrac{\mu}{\sigma} - \underset{i=1}{\overset{n}{\sum}}\left[\dfrac{X_i}{n\sigma}\right] + \dfrac{n\mu}{n\sigma} \right)^2 =\\
       &amp;= \dfrac{1}{n - 1}\underset{i=1}{\overset{n}{\sum}} \left(\dfrac{X_i}{\sigma} -\dfrac{\overline X_i}{\sigma} \right)^2 = \dfrac{1}{\sigma \cdot(n - 1)}\underset{i=1}{\overset{n}{\sum}} \left(X_i - \overline X_i \right)^2 = \dfrac{1}{\sigma}S^2_X
\end{aligned}
\]</span></p></li>
<li><p>А значить <span class="math inline">\(\dfrac{(n - 1)\cdot S^2_X}{\sigma^2} = \underset{i=1}{\overset{n}{\sum}}\left(\xi_i - \overline \xi \right)^2 \sim \chi^2_{n-1}\)</span></p></li>
</ul></li>
<li>Нехай <span class="math inline">\(\xi \sim \mathcal{N}(0, 1), \eta \sim \chi^2_k\)</span> і <span class="math inline">\(\xi\)</span> з <span class="math inline">\(\eta\)</span> незалежні. Тоді статистика <span class="math inline">\(\zeta = \dfrac{\xi}{\sqrt{\eta/k}} \sim t_{k}\)</span> — з розподілу Стьюдента<a href="#fn3" class="footnote-ref" id="fnref3" role="doc-noteref"><sup>3</sup></a> з <span class="math inline">\(k\)</span> ступенями свободи.
<ul>
<li><span class="math inline">\(\xi := \sqrt{n}\dfrac{\overline X - \mu_0}{\sigma} \sim \mathcal{N}(0, 1)\)</span></li>
<li><span class="math inline">\(\eta := \dfrac{(n - 1)\cdot S^2_X}{\sigma^2} \sim \chi^2_{n-1}\)</span></li>
<li><span class="math inline">\(\xi\)</span> и <span class="math inline">\(\eta\)</span> незалежні<a href="#fn4" class="footnote-ref" id="fnref4" role="doc-noteref"><sup>4</sup></a>.</li>
<li>Тоді <span class="math display">\[
\begin{aligned}
  t = \sqrt{n}\dfrac{\overline X - \mu_0}{\sqrt{S^2}} = \frac{\sqrt{n}\dfrac{\overline X - \mu_0}{\sigma}}{\sqrt{\dfrac{(n - 1)\cdot S^2_X}{(n - 1)\sigma^2}}} = \dfrac{\xi}{\sqrt{\dfrac{\eta}{n-1}}} \sim t_{n - 1}
\end{aligned}
\]</span></li>
</ul></li>
</ol>
<p>У підсумку, статистика <span class="math inline">\(t = \sqrt{n}\dfrac{\overline X - \mu_0}{\sqrt{S^2}} \sim t_{n - 1}\)</span> — взята з розподілу Стьюдента з <span class="math inline">\(n - 1\)</span> ступенем свободи. <strong>Але тільки в разі, якщо початкова вибірка з нормального розподілу!</strong></p>
<p>Тепер нам достатньо даних, щоб побудувати <span class="math inline">\(t\)</span>-тест:</p>
<p><span id="eq-t-test"><span class="math display">\[
H_0: \mu =\mu_0, \ X \sim \mathcal{N}\ проти\ H_1: \mu &gt; \mu_0
\tag{4.2}\]</span></span></p>
<p>Статистика <span class="math inline">\(t(X)\)</span> буде виглядати так:</p>
<p><span id="eq-t-statistic"><span class="math display">\[
t(X) = \sqrt{n}\dfrac{\overline X - \mu_0}{\sqrt{S^2}} \sim t_{n - 1}
\tag{4.3}\]</span></span></p>
<p>Тоді односторонній критерій набуває вигляду: <span id="eq-t-test-crit"><span class="math display">\[
\left\{t(X) \geq t_{n-1, 1 - \alpha} \right\}
\tag{4.4}\]</span></span></p>
<p>А <span class="math inline">\(p\)</span>-значення для одностороннього критерію можна обчислити так:</p>
<p><span id="eq-t-p-value"><span class="math display">\[
p\text{-значення} = 1 - \tau_{n-1}(z),
\tag{4.5}\]</span></span> де z — реалізація статистики <span class="math inline">\(t(X)\)</span>, <span class="math inline">\(\tau_{n-1}(z)\)</span> — функція розподілу <span class="math inline">\(t_{n - 1}\)</span></p>
<p>Двосторонній критерій буде виглядати так: <span id="eq-t-test-crit2"><span class="math display">\[
\left\{t(X) \geq t_{n-1, 1 - \frac{\alpha}{2}} \right\} \bigcup \left\{t(X) \leq -t_{n-1, 1 - \frac{\alpha}{2}} \right\}
\tag{4.6}\]</span></span></p>
<p>При цьому <span class="math inline">\(p\)</span>-значення для двостороннього критерію можна обчислити так:</p>
<p><span id="eq-t-p-value2"><span class="math display">\[
p\text{-значення} = 2\cdot \min \left[{\tau_{n-1}(z), 1 - \tau_{n-1}(z)} \right],
\tag{4.7}\]</span></span> де <span class="math inline">\(z\)</span> — реалізація статистики <span class="math inline">\(t(X)\)</span>, <span class="math inline">\(\tau_{n-1}(z)\)</span> — функція розподілу <span class="math inline">\(t_{n - 1}\)</span>.</p>
</section>
<section id="t-тест-у-python" class="level2" data-number="4.3">
<h2 data-number="4.3" class="anchored" data-anchor-id="t-тест-у-python"><span class="header-section-number">4.3</span> <span class="math inline">\(t\)</span>-тест у Python</h2>
<p>Давайте тепер протестуємо всі наші теоретичні дослідження на практиці. Для цього нам знадобляться наступні бібліотеки функції:</p>
<ul>
<li><code>scipy.stats.chii2</code> — для розподілу <span class="math inline">\(\chi^2\)</span>;</li>
<li><code>scipy.stats.t</code> — для <span class="math inline">\(t\)</span> розподілу Стюдента;</li>
<li><code>scipy.stats.ttest_1samp</code> — для <span class="math inline">\(t\)</span>-тесту.</li>
</ul>
<p>Подивимось на розподіл <span class="math inline">\(\chi^2\)</span> та розподіл <span class="math inline">\(\eta\)</span>.</p>
<div id="cell-fig-chi2" class="cell" data-execution_count="7">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a>sample_size <span class="op">=</span> <span class="dv">7</span></span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>sample_distr <span class="op">=</span> norm(loc<span class="op">=</span><span class="dv">5</span>, scale<span class="op">=</span><span class="dv">3</span>)</span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a>sample <span class="op">=</span> sample_distr.rvs(sample_size)</span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a>M <span class="op">=</span> <span class="dv">10000</span></span>
<span id="cb8-5"><a href="#cb8-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-6"><a href="#cb8-6" aria-hidden="true" tabindex="-1"></a>eta_statistic <span class="op">=</span> <span class="kw">lambda</span> sample: np.var(sample, ddof<span class="op">=</span><span class="dv">1</span>) <span class="op">*</span> (sample_size <span class="op">-</span> <span class="dv">1</span>) <span class="op">/</span> sample_distr.var()</span>
<span id="cb8-7"><a href="#cb8-7" aria-hidden="true" tabindex="-1"></a>eta_sample <span class="op">=</span> sample_statistics(</span>
<span id="cb8-8"><a href="#cb8-8" aria-hidden="true" tabindex="-1"></a>    number_of_experiments<span class="op">=</span>M, statistic_function<span class="op">=</span>eta_statistic,</span>
<span id="cb8-9"><a href="#cb8-9" aria-hidden="true" tabindex="-1"></a>    sample_size<span class="op">=</span>sample_size, sample_distr<span class="op">=</span>sample_distr</span>
<span id="cb8-10"><a href="#cb8-10" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb8-11"><a href="#cb8-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-12"><a href="#cb8-12" aria-hidden="true" tabindex="-1"></a>chi2_dist <span class="op">=</span> chi2(df<span class="op">=</span>sample_size<span class="op">-</span><span class="dv">1</span>)</span>
<span id="cb8-13"><a href="#cb8-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-14"><a href="#cb8-14" aria-hidden="true" tabindex="-1"></a>l_bound, r_bound <span class="op">=</span> np.quantile(eta_sample, [<span class="fl">0.001</span>, <span class="fl">0.999</span>])</span>
<span id="cb8-15"><a href="#cb8-15" aria-hidden="true" tabindex="-1"></a>x <span class="op">=</span> np.linspace(l_bound, r_bound, <span class="dv">1000</span>)</span>
<span id="cb8-16"><a href="#cb8-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-17"><a href="#cb8-17" aria-hidden="true" tabindex="-1"></a>sns.distplot(eta_sample, label<span class="op">=</span><span class="st">'Емпіричний розподіл'</span>, color<span class="op">=</span>turquoise)</span>
<span id="cb8-18"><a href="#cb8-18" aria-hidden="true" tabindex="-1"></a>plt.plot(x, chi2_dist.pdf(x), label<span class="op">=</span><span class="st">'$\chi^2$'</span>, color<span class="op">=</span>red_pink)</span>
<span id="cb8-19"><a href="#cb8-19" aria-hidden="true" tabindex="-1"></a>plt.legend()</span>
<span id="cb8-20"><a href="#cb8-20" aria-hidden="true" tabindex="-1"></a>plt.xlabel(<span class="st">'$\eta$'</span>)</span>
<span id="cb8-21"><a href="#cb8-21" aria-hidden="true" tabindex="-1"></a>plt.ylabel(<span class="st">'Щільність'</span>)</span>
<span id="cb8-22"><a href="#cb8-22" aria-hidden="true" tabindex="-1"></a>plt.grid(linewidth<span class="op">=</span><span class="fl">0.2</span>)</span>
<span id="cb8-23"><a href="#cb8-23" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code><button title="Скопіювати в буфер обміну" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<div id="fig-chi2" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-chi2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="t-test_files/figure-html/fig-chi2-output-1.png" width="672" height="324" class="figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-chi2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Рисунок&nbsp;4.3: Розподіл емпіричного <span class="math inline">\(\eta\)</span> та теоретичного <span class="math inline">\(\chi^2\)</span>.
</figcaption>
</figure>
</div>
</div>
</div>
<p>Ми бачимо, що емпіричний розподіл <span class="math inline">\(\eta\)</span> та теоретичний <span class="math inline">\(\chi^2\)</span> збігаються. Це означає, що ми можемо використовувати <span class="math inline">\(t\)</span>-тест для перевірки гіпотези.</p>
<p>Тепер перевіримо, чи дійсно <span class="math inline">\(t(X)\)</span> описується розподілом Стьюдента. Для цього скористаємося функцією <code>sample_statistics</code> та побудуємо гістограму для <span class="math inline">\(t(X)\)</span>. Генерувати вибірку будемо з нормального розподілу <span class="math inline">\(\mathcal{N}(5, 3^2)\)</span>.</p>
<div id="cell-fig-t-test-dist" class="cell" data-execution_count="8">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a>sample_size <span class="op">=</span> <span class="dv">7</span></span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>sample_distr <span class="op">=</span> norm(loc<span class="op">=</span><span class="dv">5</span>, scale<span class="op">=</span><span class="dv">3</span>)</span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a>sample <span class="op">=</span> sample_distr.rvs(sample_size)</span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a>M <span class="op">=</span> <span class="dv">10000</span></span>
<span id="cb9-5"><a href="#cb9-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-6"><a href="#cb9-6" aria-hidden="true" tabindex="-1"></a>T_X <span class="op">=</span> <span class="kw">lambda</span> sample: np.sqrt(sample_size) <span class="op">*</span> (np.mean(sample) <span class="op">-</span> sample_distr.mean()) <span class="op">/</span> np.std(sample, ddof<span class="op">=</span><span class="dv">1</span>)</span>
<span id="cb9-7"><a href="#cb9-7" aria-hidden="true" tabindex="-1"></a>T_sample <span class="op">=</span> sample_statistics(</span>
<span id="cb9-8"><a href="#cb9-8" aria-hidden="true" tabindex="-1"></a>    number_of_experiments<span class="op">=</span>M, statistic_function<span class="op">=</span>T_X,</span>
<span id="cb9-9"><a href="#cb9-9" aria-hidden="true" tabindex="-1"></a>    sample_size<span class="op">=</span>sample_size, sample_distr<span class="op">=</span>sample_distr</span>
<span id="cb9-10"><a href="#cb9-10" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb9-11"><a href="#cb9-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-12"><a href="#cb9-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-13"><a href="#cb9-13" aria-hidden="true" tabindex="-1"></a>T_dist <span class="op">=</span> t(df<span class="op">=</span>sample_size<span class="op">-</span><span class="dv">1</span>)</span>
<span id="cb9-14"><a href="#cb9-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-15"><a href="#cb9-15" aria-hidden="true" tabindex="-1"></a>l_bound, r_bound <span class="op">=</span> np.quantile(T_sample, [<span class="fl">0.001</span>, <span class="fl">0.999</span>])</span>
<span id="cb9-16"><a href="#cb9-16" aria-hidden="true" tabindex="-1"></a>x <span class="op">=</span> np.linspace(l_bound, r_bound, <span class="dv">1000</span>)</span>
<span id="cb9-17"><a href="#cb9-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-18"><a href="#cb9-18" aria-hidden="true" tabindex="-1"></a>sns.distplot(T_sample, color<span class="op">=</span>turquoise, label<span class="op">=</span><span class="st">'Емпіричний розподіл'</span>)</span>
<span id="cb9-19"><a href="#cb9-19" aria-hidden="true" tabindex="-1"></a>plt.plot(x, T_dist.pdf(x), c<span class="op">=</span>red_pink, label<span class="op">=</span><span class="st">'$t_{n-1}$'</span>)</span>
<span id="cb9-20"><a href="#cb9-20" aria-hidden="true" tabindex="-1"></a>plt.plot(x, norm(<span class="dv">0</span>, <span class="dv">1</span>).pdf(x), c<span class="op">=</span>slate, linestyle<span class="op">=</span><span class="st">'--'</span>, label<span class="op">=</span><span class="st">'$\mathcal</span><span class="sc">{N}</span><span class="st">(0, 1)$'</span>)</span>
<span id="cb9-21"><a href="#cb9-21" aria-hidden="true" tabindex="-1"></a>plt.legend()</span>
<span id="cb9-22"><a href="#cb9-22" aria-hidden="true" tabindex="-1"></a>plt.xlabel(<span class="st">'$t(X)$'</span>)</span>
<span id="cb9-23"><a href="#cb9-23" aria-hidden="true" tabindex="-1"></a>plt.ylabel(<span class="st">'Щільність'</span>)</span>
<span id="cb9-24"><a href="#cb9-24" aria-hidden="true" tabindex="-1"></a>plt.xlim((l_bound, r_bound))</span>
<span id="cb9-25"><a href="#cb9-25" aria-hidden="true" tabindex="-1"></a>plt.grid(linewidth<span class="op">=</span><span class="fl">0.2</span>)</span>
<span id="cb9-26"><a href="#cb9-26" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code><button title="Скопіювати в буфер обміну" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<div id="fig-t-test-dist" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-t-test-dist-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="t-test_files/figure-html/fig-t-test-dist-output-1.png" width="672" height="325" class="figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-t-test-dist-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Рисунок&nbsp;4.4: Розподіл <span class="math inline">\(t(X)\)</span>
</figcaption>
</figure>
</div>
</div>
</div>
<p>Розподіл Стьюдента практично ідеально описує дані, тоді як нормальний розподіл більш “центрований”.</p>
<p>Тепер, як викликати вбудований <span class="math inline">\(t\)</span>-тест у Python? Для цього скористаємося функцією <code>scipy.stats.ttest_1samp</code>. Вона приймає на вхід:</p>
<ul>
<li><code>a</code> — вибірка;</li>
<li><code>popmean</code> — середнє значення генеральної сукупності, яке ми хочемо перевірити;</li>
<li><code>axis</code> — вздовж якої осі обчислювати тест. За замовчуванням <code>0</code>;</li>
<li><code>nan_policy</code> — як обробляти NaN. Може приймати значення <code>propagate</code>, <code>raise</code>, <code>omit</code>. За замовчуванням <code>propagate</code>;</li>
<li><code>alternative</code> — альтернативна гіпотеза. Може приймати значення <code>two-sided</code>, <code>less</code>, <code>greater</code>. За замовчуванням <code>two-sided</code>.</li>
</ul>
<div id="b6ec31ca" class="cell" data-execution_count="9">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a>meeting_time <span class="op">=</span> np.array([<span class="dv">50</span>, <span class="dv">55</span>, <span class="dv">70</span>, <span class="dv">45</span>, <span class="dv">40</span>, <span class="dv">70</span>, <span class="dv">80</span>])</span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a>ttest_result <span class="op">=</span> ttest_1samp(meeting_time, <span class="dv">70</span>, alternative<span class="op">=</span><span class="st">'less'</span>)</span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Статистика: </span><span class="sc">{</span>ttest_result<span class="sc">.</span>statistic<span class="sc">:.2f}</span><span class="ss">"</span>)</span>
<span id="cb10-5"><a href="#cb10-5" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"p-значення: </span><span class="sc">{</span>ttest_result<span class="sc">.</span>pvalue<span class="sc">:.2f}</span><span class="ss">"</span>)</span></code><button title="Скопіювати в буфер обміну" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Статистика: -2.03
p-значення: 0.04</code></pre>
</div>
</div>
<p>Оскільки <span class="math inline">\(p\)</span>-значення менше 0.05, то ми відхиляємо нульову гіпотезу. Це означає, що середня тривалість нарад у новому форматі триває менше 70 хвилин. Відповідно до <span class="math inline">\(t\)</span>-тесту, ми можемо стверджувати, що новий формат нарад дійсно скорочує їх тривалість.</p>
</section>
<section id="довірчі-інтервали" class="level2" data-number="4.4">
<h2 data-number="4.4" class="anchored" data-anchor-id="довірчі-інтервали"><span class="header-section-number">4.4</span> Довірчі інтервали</h2>
<p>Давайте тепер розглянемо, як можна оцінити параметри генеральної сукупності за допомогою <span class="math inline">\(t\)</span>-тесту. Розглянемо два виведення довірчого інтервалу.</p>
<section id="перший-метод" class="level3" data-number="4.4.1">
<h3 data-number="4.4.1" class="anchored" data-anchor-id="перший-метод"><span class="header-section-number">4.4.1</span> Перший метод</h3>
<blockquote class="blockquote">
<p>Нехай є статистика <span class="math inline">\(Q\)</span> та критерій <span class="math inline">\(\psi(Q)\)</span> для перевірки гіпотези <span class="math inline">\(H_0: \theta = m\)</span> рівня значущості <span class="math inline">\(\alpha\)</span>.</p>
<p>Тоді довірчий інтервал для <span class="math inline">\(\theta\)</span> рівня довіри <span class="math inline">\(1 - \alpha\)</span>: множина таких <span class="math inline">\(m\)</span>, що критерій <span class="math inline">\(\psi(Q)\)</span> не відкидає для них <span class="math inline">\(H_0\)</span>.</p>
</blockquote>
<p>Нехай <span class="math inline">\(\mu\)</span> — істинне середнє вибірки. Ми також знаємо, що за <span class="math inline">\(H_0: \sqrt{n}\dfrac{\overline X - m}{\sqrt{S^2}} \sim t_{n - 1}\)</span>.</p>
<p>Нас цікавлять такі <span class="math inline">\(m\)</span>, що: <span class="math inline">\(\left\{-t_{n-1, 1 - \frac{\alpha}{2}} &lt; \sqrt{n}\dfrac{\overline X - m}{\sqrt{S^2}} &lt; t_{n-1, 1 - \frac{\alpha}{2}} \right\}\)</span>, у цьому разі критерій не відкинеться.</p>
<p>Розпишемо, щоб у центрі залишилося тільки <span class="math inline">\(m\)</span>: <span class="math inline">\(\left\{\overline X - \dfrac{t_{n - 1, 1 - \alpha/2} \sqrt{S^2}}{\sqrt{n}} &lt; m &lt; \overline X + \dfrac{t_{n - 1, 1 - \alpha/2} \sqrt{S^2}}{\sqrt{n}}\right\}\)</span>. А отже, наш довірчий інтервал:</p>
<p><span id="eq-t-interval1"><span class="math display">\[
CI_{\mu} = \left(\overline X \pm \dfrac{t_{n - 1, 1 - \alpha/2} \sqrt{S^2}}{\sqrt{n}} \right),
\tag{4.8}\]</span></span> де <span class="math inline">\(S^2 = \dfrac{1}{n - 1}\underset{i=1}{\overset{n}{\sum}}(X_i - \overline X)^2\)</span></p>
</section>
<section id="другий-метод" class="level3" data-number="4.4.2">
<h3 data-number="4.4.2" class="anchored" data-anchor-id="другий-метод"><span class="header-section-number">4.4.2</span> Другий метод</h3>
<blockquote class="blockquote">
<p>Довірчим інтервалом для параметра <span class="math inline">\(\theta\)</span> рівня довіри <span class="math inline">\(1 - \alpha\)</span> є пара статистик <span class="math inline">\(L(X), R(X)\)</span>, таких, що <span class="math inline">\(P(L(X) &lt; \theta &lt; R(X)) = 1 - \alpha\)</span>.</p>
</blockquote>
<p>Це класичне визначення довірчого інтервалу. Тобто, ми повинні знайти такі <span class="math inline">\(L(X)\)</span> та <span class="math inline">\(R(X)\)</span>, що <span class="math inline">\(P(L(X) &lt; \mu &lt; R(X)) = 1 - \alpha\)</span>.</p>
<p><span id="eq-t-interval2"><span class="math display">\[
\begin{aligned}
    &amp;t(X) = \sqrt{n}\dfrac{\overline X - \mu}{\sqrt{S^2}} \sim t_{n - 1} \Rightarrow \\
    &amp;P\left(-t_{n - 1, 1-\alpha/2} &lt; \sqrt{n}\dfrac{\overline X - \mu}{\sqrt{S^2}} &lt; t_{n - 1, 1-\alpha/2} \right) = 1 - \alpha \Leftrightarrow \\
    &amp;P\left(\overline X - \dfrac{t_{n - 1, 1 - \alpha/2} \sqrt{S^2}}{\sqrt{n}}  &lt; \mu &lt; \overline X + \dfrac{t_{n - 1, 1 - \alpha/2} \sqrt{S^2}}{\sqrt{n}} \right) = 1 - \alpha
\end{aligned}
\tag{4.9}\]</span></span></p>
<p>Тоді</p>
<p><span id="eq-t-interval3"><span class="math display">\[
CI_{\mu} = \left(\overline X \pm \dfrac{t_{n - 1, 1 - \alpha/2} \sqrt{S^2}}{\sqrt{n}} \right)
\tag{4.10}\]</span></span></p>
<p>Цей довірчий інтервал збігається з попереднім. Тобто, ми можемо використовувати обидва методи для побудови довірчого інтервалу.</p>
</section>
</section>
<section id="довірчі-інтервали-у-python" class="level2" data-number="4.5">
<h2 data-number="4.5" class="anchored" data-anchor-id="довірчі-інтервали-у-python"><span class="header-section-number">4.5</span> Довірчі інтервали у Python</h2>
<p>Давайте тепер побудуємо довірчий інтервал для середнього значення тривалості нарад у новому форматі. Для цього скористаємося функцією <code>scipy.stats.t.interval</code>. Вона приймає на вхід:</p>
<ul>
<li><code>confidence</code> — рівень значущості;</li>
<li><code>df</code> — кількість ступенів свободи;</li>
<li><code>loc</code> — середнє значення, за замовчуванням <code>0</code>;</li>
<li><code>scale</code> — стандартна девіація, за замовчуванням <code>1</code>.</li>
</ul>
<p>Для побудови лівостороннього довірчого інтервалу візьмемо <code>confidence</code> на рівні 90%, оскільки ми хочемо перевірити, чи тривалість нарад у новому форматі <em>менша</em> 70 хвилин.</p>
<div id="2edc2689" class="cell" data-execution_count="10">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a>meeting_time <span class="op">=</span> np.array([<span class="dv">50</span>, <span class="dv">55</span>, <span class="dv">70</span>, <span class="dv">45</span>, <span class="dv">40</span>, <span class="dv">70</span>, <span class="dv">80</span>])</span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a>confidence <span class="op">=</span> <span class="fl">0.90</span></span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a>df <span class="op">=</span> <span class="bu">len</span>(meeting_time) <span class="op">-</span> <span class="dv">1</span></span>
<span id="cb12-5"><a href="#cb12-5" aria-hidden="true" tabindex="-1"></a>loc <span class="op">=</span> np.mean(meeting_time)</span>
<span id="cb12-6"><a href="#cb12-6" aria-hidden="true" tabindex="-1"></a>scale <span class="op">=</span> np.std(meeting_time, ddof<span class="op">=</span><span class="dv">1</span>) <span class="op">/</span> np.sqrt(<span class="bu">len</span>(meeting_time))</span>
<span id="cb12-7"><a href="#cb12-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-8"><a href="#cb12-8" aria-hidden="true" tabindex="-1"></a>interval <span class="op">=</span> t.interval(confidence, df, loc, scale)</span>
<span id="cb12-9"><a href="#cb12-9" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Довірчий інтервал: </span><span class="sc">{</span>np<span class="sc">.</span><span class="bu">round</span>(interval, <span class="dv">2</span>)<span class="sc">}</span><span class="ss">"</span>)</span></code><button title="Скопіювати в буфер обміну" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Довірчий інтервал: [47.61 69.53]</code></pre>
</div>
</div>
</section>
<section id="t-тест-та-вимога-нормальності" class="level2" data-number="4.6">
<h2 data-number="4.6" class="anchored" data-anchor-id="t-тест-та-вимога-нормальності"><span class="header-section-number">4.6</span> <span class="math inline">\(t\)</span>-тест та вимога нормальності</h2>
<p>Ми навчилися розв’язувати задачу оцінки середнього вибірки, коли дисперсія невідома, але вибірка з нормального розподілу. Тепер розглянемо, що буде, якщо вибірка не з нормального розподілу.</p>
<div id="exm-profit" class="theorem example">
<p><span class="theorem-title"><strong>Приклад 4.2</strong></span> &nbsp;</p>
<blockquote class="blockquote">
<p>Ви запускаєте онлайн-платформу з курсами програмування. Ви плануєте надавати доступ до курсів за фіксовану плату, але також інвестуєте в маркетинг та підтримку студентів. У середньому, прибуток від одного користувача (після вирахування витрат на платформу, рекламу тощо) становить <span class="math inline">\(X\)</span> грн., але витрати на залучення кожного нового студента — 1000 грн.</p>
</blockquote>
<blockquote class="blockquote">
<p>Студенти можуть скористатися гарантією повернення грошей протягом 14 днів. Ви хочете перевірити, чи є прибуток від нових користувачів більшим за 0 грн. (тобто, чи є прибуток від нових користувачів більшим за витрати на залучення нових студентів). Тому іноді прибуток від користувача — позитивне число, а іноді — негативне.</p>
</blockquote>
<blockquote class="blockquote">
<p>Інвестори готові профінансувати вашу платформу, якщо ви доведете, що вона буде прибутковою. У вас є дані про чистий прибуток або збиток від кожного користувача, який вже зареєструвався.</p>
</blockquote>
</div>
<p>Згенеруємо штучні дані для цієї задачі. Для цього змішаємо логнормальний розподіл для позитивних значень (прибуток) та від’ємний <span class="math inline">\(\chi^2\)</span> для від’ємних значень (збиток).</p>
<div id="cell-fig-profit" class="cell" data-execution_count="11">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a>n <span class="op">=</span> <span class="dv">5000</span></span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a>p_positive <span class="op">=</span> <span class="fl">0.6</span></span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-4"><a href="#cb14-4" aria-hidden="true" tabindex="-1"></a>n_pos <span class="op">=</span> <span class="bu">int</span>(n <span class="op">*</span> p_positive)</span>
<span id="cb14-5"><a href="#cb14-5" aria-hidden="true" tabindex="-1"></a>profits <span class="op">=</span> np.random.lognormal(mean<span class="op">=</span><span class="dv">2</span>, sigma<span class="op">=</span><span class="fl">0.8</span>, size<span class="op">=</span>n_pos) <span class="op">*</span> <span class="dv">100</span></span>
<span id="cb14-6"><a href="#cb14-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-7"><a href="#cb14-7" aria-hidden="true" tabindex="-1"></a>n_neg <span class="op">=</span> n <span class="op">-</span> n_pos</span>
<span id="cb14-8"><a href="#cb14-8" aria-hidden="true" tabindex="-1"></a>losses <span class="op">=</span> <span class="op">-</span>np.random.chisquare(df<span class="op">=</span><span class="dv">2</span>, size<span class="op">=</span>n_neg) <span class="op">*</span> <span class="dv">100</span></span>
<span id="cb14-9"><a href="#cb14-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-10"><a href="#cb14-10" aria-hidden="true" tabindex="-1"></a>profits <span class="op">=</span> np.concatenate([profits, losses])</span>
<span id="cb14-11"><a href="#cb14-11" aria-hidden="true" tabindex="-1"></a>np.random.shuffle(profits)</span>
<span id="cb14-12"><a href="#cb14-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-13"><a href="#cb14-13" aria-hidden="true" tabindex="-1"></a>sns.histplot(profits, bins<span class="op">=</span><span class="dv">100</span>, kde<span class="op">=</span><span class="va">True</span>, color<span class="op">=</span>turquoise)</span>
<span id="cb14-14"><a href="#cb14-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-15"><a href="#cb14-15" aria-hidden="true" tabindex="-1"></a>plt.xlabel(<span class="st">'Прибуток або збиток'</span>)</span>
<span id="cb14-16"><a href="#cb14-16" aria-hidden="true" tabindex="-1"></a>plt.ylabel(<span class="st">'Кількість користувачів'</span>)</span>
<span id="cb14-17"><a href="#cb14-17" aria-hidden="true" tabindex="-1"></a>plt.grid(<span class="va">True</span>)</span>
<span id="cb14-18"><a href="#cb14-18" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code><button title="Скопіювати в буфер обміну" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<div id="fig-profit" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-profit-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="t-test_files/figure-html/fig-profit-output-1.png" width="682" height="324" class="figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-profit-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Рисунок&nbsp;4.5: Візуалізація штучних до задачі.
</figcaption>
</figure>
</div>
</div>
</div>
<p>Порахуємо середній прибуток.</p>
<div id="d1fc9599" class="cell" data-execution_count="12">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Середній прибуток: </span><span class="sc">{</span>profits<span class="sc">.</span>mean()<span class="sc">:.2f}</span><span class="ss">"</span>)</span></code><button title="Скопіювати в буфер обміну" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Середній прибуток: 547.45</code></pre>
</div>
</div>
<p>На відміну від попереднього завдання тут 2 відмінності:</p>
<ul>
<li>Початкова вибірка не з нормального розподілу</li>
<li>Вибірка досить велика: не 7 елементів, а вже 5000.</li>
</ul>
<section id="t-тест" class="level3" data-number="4.6.1">
<h3 data-number="4.6.1" class="anchored" data-anchor-id="t-тест"><span class="header-section-number">4.6.1</span> <span class="math inline">\(t'\)</span>-тест</h3>
<p>Згадаймо, що в нас від початку була ідея в <span class="math inline">\(Z\)</span>-тесті замість статистики <span class="math inline">\(Z\)</span>, у якій дисперсія відома, використовувати критерій <span class="math inline">\(t\)</span>, де дисперсія оцінена на даних. І використовувати нормальний розподіл. Тільки в першому завданні цей критерій нам не допоміг. Але що, якби вибірка була великою? Чи могли б ми використовувати нормальний розподіл для наближення?</p>
<ol type="1">
<li>Будемо розглядати ту саму статистику <span class="math inline">\(t = \sqrt{n}\dfrac{\overline X - \mu_0}{\sqrt{S^2}}\)</span></li>
<li><span class="math inline">\(\xi := \sqrt{n}\dfrac{\overline X - \mu_0}{\sqrt{\sigma^2}} \stackrel{d}{\rightarrow} \mathcal{N}(0, 1)\)</span>. За ЦГТ збіжність є тільки за розподілом.</li>
<li>тоді <span class="math inline">\(t = \sqrt{n}\dfrac{\overline X - \mu_0}{\sqrt{S^2}} = \xi \cdot \sqrt{\dfrac{\sigma^2}{S^2}}\)</span>. Позначимо <span class="math inline">\(\phi := \sqrt{\dfrac{\sigma^2}{S^2}}\)</span>
<ul>
<li>Пам’ятаєте, раніше було сказано, що <span class="math inline">\(S^2\)</span> — найкраща оцінка для дисперсії? Річ у тім, що вона є <a href="https://en.wikipedia.org/wiki/Consistent_estimator">консистентною</a> оцінкою для <span class="math inline">\(\sigma^2\)</span>. Тобто <span class="math inline">\(S^2\)</span> <a href="https://en.wikipedia.org/wiki/Convergence_of_random_variables#Convergence_in_probability">збігається за ймовірністю</a> до <span class="math inline">\(\sigma^2\)</span>. Тобто <span class="math inline">\(S^2 \stackrel{p}{\rightarrow} \sigma^2\)</span>.</li>
<li>А в цьому випадку існує <a href="https://en.wikipedia.org/wiki/Continuous_mapping_theorem">теорема</a>, яка стверджує, що <span class="math inline">\(\phi = \dfrac{\sigma^2}{S^2}  \stackrel{p}{\rightarrow} 1\)</span>.</li>
</ul></li>
<li><span class="math inline">\(t = \xi \cdot \phi\)</span>.
<ul>
<li><span class="math inline">\(\xi \stackrel{d}{\rightarrow} \mathcal{N}(0, 1)\)</span></li>
<li><span class="math inline">\(\phi \stackrel{p}{\rightarrow} 1\)</span></li>
<li>І тут набуває чинності ще одна <a href="https://en.wikipedia.org/wiki/Slutsky%27s_theorem">теорема</a>: <span class="math inline">\(t = \xi \cdot \phi \stackrel{d}{\rightarrow} 1\cdot \mathcal{N}(0, 1)\)</span>. Та сама збіжність, що й у ЦПТ!</li>
<li>Тобто статистика <span class="math inline">\(t\)</span> так само буде з нормального розподілу.</li>
</ul></li>
</ol>
<p>Отже, якщо вибірка велика, то ми можемо вважати, що <span class="math inline">\(t(X) \overset{H_0}{\sim} \mathcal{N}(0, 1)\)</span>.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Примітка
</div>
</div>
<div class="callout-body-container callout-body">
<p>Зауважимо, що у випадку “нормальний розподіл, велика вибірка” працюють одразу 2 критерії: <span class="math inline">\(t\)</span>-тест та <span class="math inline">\(t'\)</span>-тест. Це означає, що якщо <span class="math inline">\(t(X) \overset{H_0}{\sim} t_{n - 1}\)</span> та <span class="math inline">\(t(X) \overset{H_0}{\sim} \mathcal{N}(0, 1)\)</span>, то <span class="math inline">\(t_{n - 1} \approx \mathcal{N}(0, 1)\)</span>.</p>
<p>Формально ж, якщо ступінь свободи в <span class="math inline">\(t\)</span>-розподілі дорівнює нескінченності, то це нормальний розподіл! <span class="math inline">\(\lim_{n\rightarrow \infty}t_{n} = \mathcal{N}(0, 1)\)</span></p>
<p>А якщо <span class="math inline">\(t_{n - 1} \approx \mathcal{N}(0, 1)\)</span>, то ми замість <span class="math inline">\(t'\)</span>-критерію ми можемо використовувати <span class="math inline">\(t\)</span>-критерій!</p>
</div>
</div>
<p>В такому випадку критерій <span class="math inline">\(t\)</span>-тесту буде виглядати так:</p>
<p><span id="eq-t-test2"><span class="math display">\[
H_0: \mu =\mu_0\ проти\ H_1: \mu &gt; \mu_0
\tag{4.11}\]</span></span></p>
<p>Статистика <span class="math inline">\(t(X)\)</span> буде виглядати так:</p>
<p><span id="eq-t-statistic2"><span class="math display">\[
t(X) = \sqrt{n}\dfrac{\overline X - \mu_0}{\sqrt{S^2}}
\tag{4.12}\]</span></span></p>
<p>При достатньо великій вибірці <span class="math inline">\(t(X) \sim \mathcal{N}(0, 1)\)</span>.</p>
<p>Тоді односторонній критерій набуває вигляду:</p>
<p><span id="eq-t-test-crit2"><span class="math display">\[
\left\{t(X) \geq z_{1 - \alpha} \right\}
\tag{4.13}\]</span></span></p>
<p>А <span class="math inline">\(p\)</span>-значення для одностороннього критерію можна обчислити так:</p>
<p><span id="eq-t-p-value2"><span class="math display">\[
p\text{-значення} = 1 - \Phi(z),
\tag{4.14}\]</span></span> де <span class="math inline">\(z\)</span> — реалізація статистики <span class="math inline">\(t(X)\)</span>, <span class="math inline">\(\Phi(z)\)</span> — функція розподілу <span class="math inline">\(\mathcal{N}(0, 1)\)</span>.</p>
<p>Двосторонній критерій буде виглядати так:</p>
<p><span id="eq-t-test-crit3"><span class="math display">\[
\left\{t(X) \geq z_{1 - \frac{\alpha}{2}} \right\} \bigcup \left\{t(X) \leq -z_{1 - \frac{\alpha}{2}} \right\}
\tag{4.15}\]</span></span></p>
<p>При цьому <span class="math inline">\(p\)</span>-значення для двостороннього критерію можна обчислити так:</p>
<p><span id="eq-t-p-value3"><span class="math display">\[
p\text{-значення} = 2\cdot \min \left[{\Phi(z), 1 - \Phi(z)} \right],
\tag{4.16}\]</span></span> де <span class="math inline">\(z\)</span> — реалізація статистики <span class="math inline">\(t(X)\)</span>, <span class="math inline">\(\Phi(z)\)</span> — функція розподілу <span class="math inline">\(\mathcal{N}(0, 1)\)</span>.</p>
<p>Перевіримо наш критерій на великій вибірці. Для цього згеренуємо вибірку з експоненційного розподілу <span class="math inline">\(\mathcal{E}(300)\)</span>, де <span class="math inline">\(X \sim \mathcal{E}(\lambda)\)</span>, <span class="math inline">\(\lambda = 1/\mu\)</span>. Вибірка буде згенерована з параметром <span class="math inline">\(\lambda = 1/300\)</span>. Тобто, середнє значення вибірки буде <span class="math inline">\(300\)</span>.</p>
<div id="cell-fig-profit-test" class="cell" data-execution_count="13">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a>sample_size<span class="op">=</span><span class="dv">2000</span></span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a>M <span class="op">=</span> <span class="dv">10000</span></span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a>sample_distr <span class="op">=</span> expon(loc<span class="op">=</span><span class="dv">5</span>, scale<span class="op">=</span><span class="dv">300</span>)</span>
<span id="cb17-4"><a href="#cb17-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-5"><a href="#cb17-5" aria-hidden="true" tabindex="-1"></a>T_X <span class="op">=</span> <span class="kw">lambda</span> sample: np.sqrt(sample_size) <span class="op">*</span> (np.mean(sample) <span class="op">-</span> sample_distr.mean()) <span class="op">/</span> np.std(sample, ddof<span class="op">=</span><span class="dv">1</span>)</span>
<span id="cb17-6"><a href="#cb17-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-7"><a href="#cb17-7" aria-hidden="true" tabindex="-1"></a>T_sample <span class="op">=</span> sample_statistics(</span>
<span id="cb17-8"><a href="#cb17-8" aria-hidden="true" tabindex="-1"></a>    number_of_experiments<span class="op">=</span>M, statistic_function<span class="op">=</span>T_X,</span>
<span id="cb17-9"><a href="#cb17-9" aria-hidden="true" tabindex="-1"></a>    sample_size<span class="op">=</span>sample_size, sample_distr<span class="op">=</span>sample_distr)</span>
<span id="cb17-10"><a href="#cb17-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-11"><a href="#cb17-11" aria-hidden="true" tabindex="-1"></a>l_bound, r_bound <span class="op">=</span> np.quantile(T_sample, [<span class="fl">0.001</span>, <span class="fl">0.999</span>])</span>
<span id="cb17-12"><a href="#cb17-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-13"><a href="#cb17-13" aria-hidden="true" tabindex="-1"></a>x <span class="op">=</span> np.linspace(l_bound, r_bound, <span class="dv">1000</span>)</span>
<span id="cb17-14"><a href="#cb17-14" aria-hidden="true" tabindex="-1"></a>sns.distplot(T_sample, label<span class="op">=</span><span class="st">'Емпіричний розподіл'</span>, color<span class="op">=</span>turquoise)</span>
<span id="cb17-15"><a href="#cb17-15" aria-hidden="true" tabindex="-1"></a>plt.plot(x, norm(<span class="dv">0</span>, <span class="dv">1</span>).pdf(x), label<span class="op">=</span><span class="st">'Експоненціальний розподіл'</span>, color<span class="op">=</span>red_pink)</span>
<span id="cb17-16"><a href="#cb17-16" aria-hidden="true" tabindex="-1"></a>plt.legend()</span>
<span id="cb17-17"><a href="#cb17-17" aria-hidden="true" tabindex="-1"></a>plt.xlabel(<span class="ss">f'</span><span class="sc">{</span>name<span class="sc">}</span><span class="ss">'</span>)</span>
<span id="cb17-18"><a href="#cb17-18" aria-hidden="true" tabindex="-1"></a>plt.xlim((l_bound, r_bound))</span>
<span id="cb17-19"><a href="#cb17-19" aria-hidden="true" tabindex="-1"></a>plt.ylabel(<span class="st">'Щільність'</span>)</span>
<span id="cb17-20"><a href="#cb17-20" aria-hidden="true" tabindex="-1"></a>plt.grid(linewidth<span class="op">=</span><span class="fl">0.2</span>)</span>
<span id="cb17-21"><a href="#cb17-21" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code><button title="Скопіювати в буфер обміну" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<div id="fig-profit-test" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-profit-test-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="t-test_files/figure-html/fig-profit-test-output-1.png" width="672" height="324" class="figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-profit-test-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Рисунок&nbsp;4.6: Розподіл <span class="math inline">\(t'(X)\)</span> для великої вибірки.
</figcaption>
</figure>
</div>
</div>
</div>
<p>Ми бачимо, що емпіричний розподіл <span class="math inline">\(t'(X)\)</span> та теоретичний <span class="math inline">\(\mathcal{N}(0, 1)\)</span> збігаються. Це означає, що ми можемо використовувати <span class="math inline">\(t'\)</span>-тест для перевірки гіпотези. Якщо ж перевірити на великих вибірках з нормального розподілу, то <span class="math inline">\(t\)</span>-тест та <span class="math inline">\(t'\)</span>-тест будуть давати доволі схожі результати.</p>
<div id="cell-fig-t-test-dist2" class="cell" data-execution_count="14">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a>sample_size<span class="op">=</span><span class="dv">2000</span></span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a>M <span class="op">=</span> <span class="dv">30000</span></span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a>sample_distr <span class="op">=</span> norm(loc<span class="op">=</span><span class="dv">5</span>, scale<span class="op">=</span><span class="dv">300</span>)</span>
<span id="cb18-4"><a href="#cb18-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-5"><a href="#cb18-5" aria-hidden="true" tabindex="-1"></a>T_X <span class="op">=</span> <span class="kw">lambda</span> sample: np.sqrt(sample_size) <span class="op">*</span> (np.mean(sample) <span class="op">-</span> sample_distr.mean()) <span class="op">/</span> np.std(sample, ddof<span class="op">=</span><span class="dv">1</span>)</span>
<span id="cb18-6"><a href="#cb18-6" aria-hidden="true" tabindex="-1"></a>T_sample <span class="op">=</span> sample_statistics(</span>
<span id="cb18-7"><a href="#cb18-7" aria-hidden="true" tabindex="-1"></a>    number_of_experiments<span class="op">=</span>M, statistic_function<span class="op">=</span>T_X,</span>
<span id="cb18-8"><a href="#cb18-8" aria-hidden="true" tabindex="-1"></a>    sample_size<span class="op">=</span>sample_size, sample_distr<span class="op">=</span>sample_distr)</span>
<span id="cb18-9"><a href="#cb18-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-10"><a href="#cb18-10" aria-hidden="true" tabindex="-1"></a>l_bound, r_bound <span class="op">=</span> np.quantile(T_sample, [<span class="fl">0.001</span>, <span class="fl">0.999</span>])</span>
<span id="cb18-11"><a href="#cb18-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-12"><a href="#cb18-12" aria-hidden="true" tabindex="-1"></a>x <span class="op">=</span> np.linspace(l_bound, r_bound, <span class="dv">1000</span>)</span>
<span id="cb18-13"><a href="#cb18-13" aria-hidden="true" tabindex="-1"></a>sns.distplot(T_sample, label<span class="op">=</span><span class="st">'Емпіричний розподіл'</span>, color<span class="op">=</span>turquoise)</span>
<span id="cb18-14"><a href="#cb18-14" aria-hidden="true" tabindex="-1"></a>plt.plot(x, norm(<span class="dv">0</span>, <span class="dv">1</span>).pdf(x), label<span class="op">=</span><span class="st">'$\mathcal</span><span class="sc">{N}</span><span class="st">(0, 1)$'</span>, color<span class="op">=</span>red_pink)</span>
<span id="cb18-15"><a href="#cb18-15" aria-hidden="true" tabindex="-1"></a>plt.legend()</span>
<span id="cb18-16"><a href="#cb18-16" aria-hidden="true" tabindex="-1"></a>plt.xlabel(<span class="ss">f'</span><span class="sc">{</span>name<span class="sc">}</span><span class="ss">'</span>)</span>
<span id="cb18-17"><a href="#cb18-17" aria-hidden="true" tabindex="-1"></a>plt.xlim((l_bound, r_bound))</span>
<span id="cb18-18"><a href="#cb18-18" aria-hidden="true" tabindex="-1"></a>plt.ylabel(<span class="st">'Щільність'</span>)</span>
<span id="cb18-19"><a href="#cb18-19" aria-hidden="true" tabindex="-1"></a>plt.grid(linewidth<span class="op">=</span><span class="fl">0.2</span>)</span>
<span id="cb18-20"><a href="#cb18-20" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code><button title="Скопіювати в буфер обміну" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<div id="fig-t-test-dist2" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-t-test-dist2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="t-test_files/figure-html/fig-t-test-dist2-output-1.png" width="672" height="324" class="figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-t-test-dist2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Рисунок&nbsp;4.7: Розподіл <span class="math inline">\(t(X)\)</span> для великої вибірки.
</figcaption>
</figure>
</div>
</div>
</div>
<p>Виходить, що статистика <span class="math inline">\(t'(X)\)</span> при великій вибірці з нормального розподілу також буде з нормального розподілу.</p>
</section>
</section>
<section id="довірчий-інтервал" class="level2" data-number="4.7">
<h2 data-number="4.7" class="anchored" data-anchor-id="довірчий-інтервал"><span class="header-section-number">4.7</span> Довірчий інтервал</h2>
<p>Довірчий інтревал виводиться аналогічно до <span class="math inline">\(t\)</span>-тесту.</p>
<p><span id="eq-t-interval4"><span class="math display">\[
\begin{aligned}
    &amp;t'(X) = \sqrt{n}\dfrac{\overline X - \mu}{\sqrt{S^2}} \sim \mathcal{N}(0, 1) \Rightarrow \\
    &amp;P\left(-z_{1 - \frac{\alpha}{2}} &lt; \sqrt{n}\dfrac{\overline X - \mu}{\sqrt{S^2}} &lt; z_{1 - \frac{\alpha}{2}} \right) = 1 - \alpha \Leftrightarrow \\
    &amp;P\left(\overline X - \dfrac{z_{1 - \frac{\alpha}{2}} S^2}{\sqrt{n}}  &lt; \mu &lt; \overline X + \dfrac{z_{1 - \frac{\alpha}{2}} S^2}{\sqrt{n}} \right) = 1 - \alpha
\end{aligned}
\tag{4.17}\]</span></span></p>
<p>Переглнемо на практиці, як це виглядає у Python.</p>
<div id="1a691b12" class="cell" data-execution_count="15">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a>sample <span class="op">=</span> expon(scale<span class="op">=</span><span class="dv">300</span>).rvs(<span class="dv">2000</span>)</span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a>ci <span class="op">=</span> norm.interval(confidence<span class="op">=</span><span class="fl">0.95</span>, loc<span class="op">=</span>np.mean(sample), scale<span class="op">=</span>sem(sample))</span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"CI = </span><span class="sc">{</span>np<span class="sc">.</span><span class="bu">round</span>(ci, <span class="dv">2</span>)<span class="sc">}</span><span class="ss">"</span>)</span></code><button title="Скопіювати в буфер обміну" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>CI = [293.89 319.75]</code></pre>
</div>
</div>
<p>Тепер ми можемо повернутися до нашої задачі з прибутком.</p>
<div id="009b0c10" class="cell" data-execution_count="16">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a>ci_profit <span class="op">=</span> norm.interval(confidence<span class="op">=</span><span class="fl">0.95</span>, loc<span class="op">=</span>np.mean(profits), scale<span class="op">=</span>sem(profits))</span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"CI = </span><span class="sc">{</span>np<span class="sc">.</span><span class="bu">round</span>(ci_profit, <span class="dv">2</span>)<span class="sc">}</span><span class="ss">"</span>)</span></code><button title="Скопіювати в буфер обміну" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>CI = [520.19 574.72]</code></pre>
</div>
</div>
<p>Це означає, що ми можемо стверджувати, що прибуток від нових користувачів більший за 0 грн.</p>
</section>
<section id="вибір-критерію" class="level2" data-number="4.8">
<h2 data-number="4.8" class="anchored" data-anchor-id="вибір-критерію"><span class="header-section-number">4.8</span> Вибір критерію</h2>
<p>Для початку визначимося, коли який критерій краще використовувати?</p>
<ol type="1">
<li>Якщо вибірка розміру 60, то вже <span class="math inline">\(t_{59} \approx \mathcal{N}(0, 1)\)</span>.
<ul>
<li>Подивимося на розподіли Стьюдента і нормального:</li>
</ul></li>
</ol>
<div id="cell-fig-t-test-dist3" class="cell" data-execution_count="17">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a>df <span class="op">=</span> <span class="dv">59</span></span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a>t_dist <span class="op">=</span> t(df<span class="op">=</span>df)</span>
<span id="cb23-3"><a href="#cb23-3" aria-hidden="true" tabindex="-1"></a>z_dist <span class="op">=</span> norm(loc<span class="op">=</span><span class="dv">0</span>, scale<span class="op">=</span><span class="dv">1</span>)</span>
<span id="cb23-4"><a href="#cb23-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-5"><a href="#cb23-5" aria-hidden="true" tabindex="-1"></a>x <span class="op">=</span> np.linspace(<span class="op">-</span><span class="dv">3</span>, <span class="dv">3</span>, <span class="dv">100</span>)</span>
<span id="cb23-6"><a href="#cb23-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-7"><a href="#cb23-7" aria-hidden="true" tabindex="-1"></a>plt.plot(x, z_dist.pdf(x), label<span class="op">=</span><span class="st">'$\mathcal</span><span class="sc">{N}</span><span class="st">(0, 1)$'</span>, color<span class="op">=</span>red_pink)</span>
<span id="cb23-8"><a href="#cb23-8" aria-hidden="true" tabindex="-1"></a>plt.plot(x, t_dist.pdf(x), label<span class="op">=</span><span class="st">'$t_</span><span class="sc">{59}</span><span class="st">$'</span>, color<span class="op">=</span>turquoise)</span>
<span id="cb23-9"><a href="#cb23-9" aria-hidden="true" tabindex="-1"></a>plt.legend()</span>
<span id="cb23-10"><a href="#cb23-10" aria-hidden="true" tabindex="-1"></a>plt.grid(linewidth<span class="op">=</span><span class="fl">0.2</span>)</span>
<span id="cb23-11"><a href="#cb23-11" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code><button title="Скопіювати в буфер обміну" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<div id="fig-t-test-dist3" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-t-test-dist3-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="t-test_files/figure-html/fig-t-test-dist3-output-1.png" width="652" height="304" class="figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-t-test-dist3-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Рисунок&nbsp;4.8: Розподіл <span class="math inline">\(t(X)\)</span> та <span class="math inline">\(N(0, 1)\)</span>.
</figcaption>
</figure>
</div>
</div>
</div>
<ul>
<li>Ми бачимо, що ці два розподіли візуально повністю збігаються, тому неважливо, як порахувати: статистика <span class="math inline">\(t\sim \mathcal{N}(0, 1)\)</span> або <span class="math inline">\(t\sim t_n\)</span>.</li>
<li>Але це не означає, що з <span class="math inline">\(N=60\)</span> <span class="math inline">\(t\)</span>-тест або <span class="math inline">\(t'\)</span>-тест працюють коректно! Якщо вибірка не з нормального розподілу, вони обидва можуть усе ще помилятися.</li>
</ul>
<ol start="2" type="1">
<li>Якщо вибірка менше 60, то безпечніше використовувати <span class="math inline">\(t\)</span>-тест, ніж <span class="math inline">\(t'\)</span>-тест.
<ul>
<li><strong>У <span class="math inline">\(t\)</span>-тест FPR завжди буде меншим, ніж у <span class="math inline">\(t'\)</span>-тест</strong>.
<ul>
<li>На FPR впливає відсоток випадків <code>pvalue &lt; alpha</code>. У <span class="math inline">\(t\)</span>-тест <span class="math inline">\(p\)</span>-значення <span class="math inline">\(\geq\)</span> <span class="math inline">\(t'\)</span>-тест <span class="math inline">\(p\)</span>-значення.</li>
<li><code>pvalue = t_distr.cdf(x)</code> або <code>pvalue = norm_dist.cdf(x)</code>. Тож чим важчий хвіст у розподілу, тим більше <span class="math inline">\(p\)</span>-значення.</li>
</ul></li>
</ul></li>
</ol>
<p>Подивимось на прикладі.</p>
<div id="cell-fig-t-test-dist4" class="cell" data-execution_count="18">
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a>df_array <span class="op">=</span> [<span class="dv">2</span>, <span class="dv">5</span>, <span class="dv">10</span>, <span class="dv">20</span>]</span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a>x <span class="op">=</span> np.linspace(<span class="op">-</span><span class="dv">3</span>, <span class="dv">3</span>, <span class="dv">100</span>)</span>
<span id="cb24-3"><a href="#cb24-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-4"><a href="#cb24-4" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> df <span class="kw">in</span> df_array:</span>
<span id="cb24-5"><a href="#cb24-5" aria-hidden="true" tabindex="-1"></a>    t_dist <span class="op">=</span> t(df<span class="op">=</span>df)</span>
<span id="cb24-6"><a href="#cb24-6" aria-hidden="true" tabindex="-1"></a>    plt.plot(x, t_dist.cdf(x), label<span class="op">=</span><span class="ss">f't(df=</span><span class="sc">{</span>df<span class="sc">}</span><span class="ss">)'</span>)</span>
<span id="cb24-7"><a href="#cb24-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-8"><a href="#cb24-8" aria-hidden="true" tabindex="-1"></a>z_dist <span class="op">=</span> norm(loc<span class="op">=</span><span class="dv">0</span>, scale<span class="op">=</span><span class="dv">1</span>)</span>
<span id="cb24-9"><a href="#cb24-9" aria-hidden="true" tabindex="-1"></a>plt.plot(x, z_dist.cdf(x), c<span class="op">=</span>red_pink, label<span class="op">=</span><span class="st">'$\mathcal</span><span class="sc">{N}</span><span class="st">(0, 1)$'</span>)</span>
<span id="cb24-10"><a href="#cb24-10" aria-hidden="true" tabindex="-1"></a>plt.legend()</span>
<span id="cb24-11"><a href="#cb24-11" aria-hidden="true" tabindex="-1"></a>plt.xlabel(<span class="st">'X'</span>)</span>
<span id="cb24-12"><a href="#cb24-12" aria-hidden="true" tabindex="-1"></a>plt.grid(linewidth<span class="op">=</span><span class="fl">0.2</span>)</span>
<span id="cb24-13"><a href="#cb24-13" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code><button title="Скопіювати в буфер обміну" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<div id="fig-t-test-dist4" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-t-test-dist4-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="t-test_files/figure-html/fig-t-test-dist4-output-1.png" width="646" height="324" class="figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-t-test-dist4-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Рисунок&nbsp;4.9: Куртки розподілів <span class="math inline">\(t\)</span> та <span class="math inline">\(N(0, 1)\)</span>.
</figcaption>
</figure>
</div>
</div>
</div>
<p>Як видно на графіку, що менший ступінь свободи, то вищою є лінія на графіку (за x &lt; 0), а отже <span class="math inline">\(P(X &lt; x)\)</span> буде більшим, ніж у нормальному розподілі. Тобто, <span class="math inline">\(t\)</span>-тест буде давати менше <span class="math inline">\(p\)</span>-значення, ніж <span class="math inline">\(t'\)</span>-тест. А отже, <span class="math inline">\(t\)</span>-тест буде відкидати нульову гіпотезу частіше, ніж <span class="math inline">\(t'\)</span>-тест.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Примітка
</div>
</div>
<div class="callout-body-container callout-body">
<p>Розподіл Стьюдента з нескінченністю ступенів свободи — це нормальний розподіл: <span class="math inline">\(t_{\infty} = \mathcal{N}(0, 1)\)</span>. Тому <code>norm(0, 1).cdf(x) = t_distr(df=infinity).cdf(x) &lt; t_distr(df=N).cdf(x)</code>.</p>
</div>
</div>
<p>Тому, якщо вибірка невелика, безпечніше використовувати <span class="math inline">\(t\)</span>-тест. Але все ще не факт, що ваш критерій буде валідний!</p>
<p>Ми бачимо, що ми скрізь можемо використовувати <span class="math inline">\(t\)</span>-тест (а <span class="math inline">\(t'\)</span>-тест не завжди), і в разі маленьких вибірок він безпечніший. <strong>Тому <span class="math inline">\(t\)</span>-тест і став набагато популярнішим, ніж <span class="math inline">\(t'\)</span>-тест</strong>. Але <span class="math inline">\(t'\)</span>-тест на практиці може бути теж корисний:</p>
<ul>
<li>Не треба думати під час реалізації про ступені свободи.</li>
<li>Написати такий критерій на SQL буде набагато простіше: ви можете використовувати табличні значення в коді, щоб зрозуміти, чи відкинувся критерій.</li>
<li>Робити різні теоретичні обчислення простіше.</li>
<li>У ньому складніше помилитися під час реалізації.</li>
</ul>
</section>
<section id="мінімальний-ефект" class="level2" data-number="4.9">
<h2 data-number="4.9" class="anchored" data-anchor-id="мінімальний-ефект"><span class="header-section-number">4.9</span> Мінімальний ефект</h2>
<p>Повернемося до завдання зі стартапом. Уявімо, що ми хочемо запустити наш стартап на новому ринку, наприклад у іншій країні. <strong>Питання: чи можемо ми зменшити розмір вибірки?</strong></p>
<p>Що взагалі нам заважає взяти занадто маленьку вибірку? Наприклад, якщо ми перевіряємо наш стартап на 1-2 користувачів, то ми нічого не можемо сказати про наш істинний ефект, він може бути як більшим за 0, так і меншим. Буде занадто широкий довірчий інтервал (через велику дисперсію у вибірці), і нам потрібен величезний ефект, щоб його виявити.</p>
<p>Ще, можливо, ми не можемо використовувати критерій на такій маленькій вибірці. А якщо вибірка складалася б із нескінченної кількості користувачів, то ми могли б абсолютно точно сказати справжній прибуток від користувача, навіть якщо він дорівнює 1 копійці. При цьому обидва випадки нас не влаштовують. У першому — ми не зможемо запустити стартап через занадто великий шум, а в другому — нам потрібна вічність, щоб перевірити нашу гіпотезу.</p>
<p>І тут нам допоможе MDE (minimum detectable effect). Це таке істинне значення ефекту, що наш шанс його виявити дорівнює <span class="math inline">\(1-\beta\)</span> при використанні нашого критерію.</p>
<p>Ми можемо подивитись, який ефект ми зможемо зафіксувати під меншої кількості користувачів, і від цього вирішити, чи підходить нам така вибірка, чи ні. Наприклад:</p>
<ul>
<li>Ми бачимо, що MDE 100 гривень. Тобто з ймовірністю <span class="math inline">\(1-\beta\)</span> (на практиці 80%) ми його виявимо, <strong>якщо такий ефект буде</strong>. І з імовірністю 80% стартап запуститься на новому ринку. Чудово, це нас влаштовує, ми перевіряємо гіпотезу на меншій вибірці.</li>
<li>Ми бачимо, що MDE 10000 гривень. Це, навпаки, занадто багато: у нас 99% послуг коштують менше 1000 гривень. Ми не наберемо такого прибутку, стартап невиграшний, потрібно брати вибірку більшого розміру.</li>
</ul>
<p>Тому слід чітко визначити <strong>від чого залежить MDE</strong>. Це може бути:</p>
<ul>
<li><em>Помилка першого роду</em>, або <span class="math inline">\(\alpha\)</span>. Наприклад, за <span class="math inline">\(\alpha = 1\)</span> ми знайдемо ефект і за розміру вибірки, що дорівнює одиниці (ми просто завжди відкидатимемо <span class="math inline">\(H_0\)</span>). А за <span class="math inline">\(\alpha = 0\)</span> ми ніколи не зафіксуємо ефект.</li>
<li><em>Потужність</em>, або <span class="math inline">\(1 - \beta\)</span>. Випливає із самого визначення.</li>
<li>Від <em>шуму в даних</em>, або від <em>дисперсії</em>. Що більш шумні дані, як ми знаємо, то ширший довірчий інтервал. А отже, складніше точно передбачити межі для істинного ефекту, тому й MDE буде більшим.</li>
<li>Від <em>розміру вибірки</em>. Нас цікавить не просто дисперсія в даних, а дисперсія середнього значення: вона за тією самою логікою має бути якомога меншою. А що таке дисперсія середнього? Це <span class="math inline">\(\dfrac{\sigma^2}{N}\)</span>, тому MDE також залежить від розміру вибірки.</li>
</ul>
<p>Тепер давайте виведемо формулу виходячи з того, що ми знаємо всі ці чотири параметри. Для початку визначимося з гіпотезою, що перевіряється:</p>
<p><span id="eq-t-test-h0"><span class="math display">\[
H_0: \mu_0 = 0\ проти. \ H_1: \mu_0 &gt; 0
\tag{4.18}\]</span></span></p>
<p>Позначимо оцінку дисперсії середнього значення:</p>
<p><span id="eq-t-test-s2"><span class="math display">\[
S^2_{\mu} := \frac{S^2}{N}
\tag{4.19}\]</span></span></p>
<p>А також стандартне відхилення середнього значення:</p>
<p><span id="eq-t-test-s-mu"><span class="math display">\[
S_{\mu} = \sqrt{\frac{S^2}{N}}
\tag{4.20}\]</span></span></p>
<p>Тепер ми знаємо, що</p>
<p><span id="eq-t-test-x"><span class="math display">\[
\overline X \sim \mathcal{N}(\mu, S^2_{\mu})
\tag{4.21}\]</span></span></p>
<p>Нам треба знайти <span class="math inline">\(\text{MDE}=m\)</span>, таке, що:</p>
<ul>
<li>якщо <span class="math inline">\(\overline X \sim \mathcal{N}(m, S^2_{\mu})\)</span>, то в <span class="math inline">\(1-\beta\)</span> відсотку випадків для нього відкинеться критерій. Перевіряємо потужність (ціанова площа на графіку).</li>
<li>якщо <span class="math inline">\(\overline X \sim \mathcal{N}(0, S^2_{\mu})\)</span>, то критерій відкинеться для нього в <span class="math inline">\(\alpha\)</span> відсотків випадків. Перевіряємо FPR (рожева площа на графіку).</li>
</ul>
<div id="cell-fig-mde" class="cell" data-execution_count="19">
<div class="cell-output cell-output-display">
<div id="fig-mde" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-mde-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="t-test_files/figure-html/fig-mde-output-1.png" width="678" height="327" class="figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-mde-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Рисунок&nbsp;4.10: Графік MDE.
</figcaption>
</figure>
</div>
</div>
</div>
<p>Нехай</p>
<p><span id="eq-t-test-b"><span class="math display">\[
B(X): P_{H_0}(\overline X &gt; B(X)) = \alpha,
\tag{4.22}\]</span></span> де <span class="math inline">\(B(X)\)</span> — межа відхилення нульової гіпотези.</p>
<p>Тоді</p>
<p><span id="eq-t-test-p"><span class="math display">\[
P_{H_1}(\overline X &gt; B(X)) = 1-\beta
\tag{4.23}\]</span></span></p>
<p>Або</p>
<p><span id="eq-t-test-p-m"><span class="math display">\[
P_{H_1}(\overline X - m &gt; B(X) - m) = 1-\beta
\tag{4.24}\]</span></span></p>
<p>Позначимо <span class="math inline">\(\xi := \overline X - m\)</span>. Тоді</p>
<p><span id="eq-t-test-p-xi"><span class="math display">\[
P_{H_0}(\xi &gt; B(X) - m) = 1-\beta,
\tag{4.25}\]</span></span> де <span class="math inline">\(B(X) - m\)</span> — межа відхилення нульової гіпотези з урахуванням істинного ефекту.</p>
<p>Треба розв’язати ці 2 рівняння й ми отримаємо вираз <span class="math inline">\(m\)</span> через усі чотири параметри.</p>
<p>За <span class="math inline">\(H_0\)</span> наш критерій має такий вигляд:</p>
<p><span id="eq-t-test-b-xi"><span class="math display">\[
\left\{T(X) \geq z_{1 - \alpha} \right\} \Leftrightarrow  \left\{\sqrt{N}\dfrac{\overline X}{\sqrt{S^2}} \geq z_{1 - \alpha} \right\} \Leftrightarrow B(X) = z_{1 - \alpha}\sqrt{\frac{S^2}{N}} = z_{1 - \alpha}S_{\mu}
\tag{4.26}\]</span></span></p>
<p>Тоді</p>
<p><span id="eq-t-test-p-xi2"><span class="math display">\[
P_{H_0}(\xi &gt; z_{1 - \alpha}S_{\mu} - m) = 1-\beta
\tag{4.27}\]</span></span></p>
<p>Але працювати з розподілом <span class="math inline">\(\mathcal{N}(0, S^2_{\mu})\)</span> не дуже зручно, набагато простіше з <span class="math inline">\(\mathcal{N}(0, 1)\)</span>. Для цього переходу достатньо перейти від <span class="math inline">\(\xi \rightarrow \dfrac{\xi}{S_{\mu}}\)</span> за властивостями нормального розподілу.</p>
<p>Позначимо <span class="math inline">\(\eta := \dfrac{\xi}{S_{\mu}}\)</span>. Тоді</p>
<p><span id="eq-t-test-p-xi3"><span class="math display">\[
\begin{aligned}
    &amp;P_{H_0}(\xi &gt; z_{1 - \alpha}S_{\mu} - m) =\\
    &amp;P_{H_0}(\dfrac{\xi}{S_{\mu}} &gt; \dfrac{z_{1 - \alpha}S_{\mu} - m}{S_{\mu}}) =\\
    &amp; P_{\mathcal{N}(0, 1)}(\eta &gt; z_{1 - \alpha} - \dfrac{m}{S_{\mu}}) = 1-\beta
\end{aligned}
\tag{4.28}\]</span></span></p>
<p>За умови <span class="math inline">\(\Phi(C) = P(\eta &lt; C)\)</span>, тоді</p>
<p><span id="eq-t-test-p-xi4"><span class="math display">\[
\begin{aligned}
&amp;1 - \Phi \left(z_{1 - \alpha} - \dfrac{m}{S_{\mu}} \right) = 1-\beta \Leftrightarrow\\ &amp;z_{1 - \alpha} - \dfrac{m}{S_{\mu}} = z_{\beta},
\end{aligned}
\tag{4.29}\]</span></span> де <span class="math inline">\(z_{\beta} = \Phi^{-1}(\beta)\)</span> — квантиль <span class="math inline">\(\beta\)</span> нормального розподілу.</p>
<p>Тепер згадаємо, що <span class="math inline">\(\eta \sim \mathcal{N}(0, 1)\)</span>, тоді</p>
<p><span id="eq-t-test-m"><span class="math display">\[
m = (z_{1 - \alpha} - z_{\beta}) \cdot S_{\mu} = (z_{1 - \alpha} + z_{1 - \beta}) \cdot \sqrt{\frac{S^2}{N}}
\tag{4.30}\]</span></span></p>
<p>Отже, ми отримали формулу для MDE:</p>
<p><span id="eq-t-test-mde"><span class="math display">\[
\text{MDE} = (z_{1 - \alpha} + z_{1 - \beta}) \cdot \sqrt{\frac{S^2}{N}}
\tag{4.31}\]</span></span> де <span class="math inline">\(z_{1 - \alpha}\)</span> — квантиль <span class="math inline">\(\alpha\)</span> нормального розподілу, <span class="math inline">\(z_{1 - \beta}\)</span> — квантиль <span class="math inline">\(\beta\)</span> нормального розподілу, <span class="math inline">\(S^2\)</span> — оцінка дисперсії, <span class="math inline">\(N\)</span> — розмір вибірки.</p>
<p>Повернемося до стартапу. Припустимо, що <span class="math inline">\(N = 1000\)</span>, <span class="math inline">\(\alpha=5\)</span>%, <span class="math inline">\(1-\beta=80\)</span>%, а як дізнатися <span class="math inline">\(S^2\)</span>?</p>
<p>На практиці є 3 способи:</p>
<ul>
<li>Оцінити на історичних даних. У цьому випадку це не підходить, тому що раніше стартапу на новому ринку не було.</li>
<li>Оцінити за схожими даними. Наприклад, у нашому випадку, оцінити дисперисію на початковому ринку.</li>
<li>Якось теоретично оцінити. Найгірший спосіб, який працює, якщо перші два не допомагають.</li>
</ul>
<p>Подивимося тепер MDE у нашому завданні.</p>
<div id="5dd95b94" class="cell" data-execution_count="20">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a>N <span class="op">=</span> <span class="dv">1000</span></span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a>S2 <span class="op">=</span> np.var(profits)</span>
<span id="cb25-3"><a href="#cb25-3" aria-hidden="true" tabindex="-1"></a>alpha <span class="op">=</span> <span class="fl">0.05</span></span>
<span id="cb25-4"><a href="#cb25-4" aria-hidden="true" tabindex="-1"></a>beta <span class="op">=</span> <span class="dv">1</span> <span class="op">-</span> <span class="fl">0.8</span></span>
<span id="cb25-5"><a href="#cb25-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-6"><a href="#cb25-6" aria-hidden="true" tabindex="-1"></a>MDE <span class="op">=</span> (norm().ppf(<span class="dv">1</span><span class="op">-</span>alpha) <span class="op">+</span> norm().ppf(<span class="dv">1</span> <span class="op">-</span> beta)) <span class="op">*</span> np.sqrt(S2<span class="op">/</span>N)</span>
<span id="cb25-7"><a href="#cb25-7" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"MDE при N = </span><span class="sc">{</span>N<span class="sc">}</span><span class="ss">: </span><span class="sc">{</span>np<span class="sc">.</span><span class="bu">round</span>(MDE, <span class="dv">2</span>)<span class="sc">}</span><span class="ss">"</span>)</span></code><button title="Скопіювати в буфер обміну" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>MDE при N = 1000: 77.33</code></pre>
</div>
</div>
<p>А отже, ми можемо розраховувати на точність лише в 77.33 грн. Але дня нас це може бути занадто великий MDE: хочеться, щоб він був <span class="math inline">\(\leq\)</span> 50 грн, ми припускаємо, що це ймовірніший істинний ефект, виходячи з поперелднього досвіду.</p>
<p>Давайте тепер розв’яжемо зворотну задачу: Ми знаємо <span class="math inline">\(MDE=50\)</span> грн., <span class="math inline">\(\alpha=5\)</span>%, <span class="math inline">\(1-\beta=80\)</span>%, <span class="math inline">\(S^2\)</span>, чому дорівнює <span class="math inline">\(N\)</span>? Виведемо його з формули MDE:</p>
<p><span id="eq-t-test-n"><span class="math display">\[
N = \left(\dfrac{z_{1 - \alpha} + z_{1 - \beta}}{\text{MDE}}\right)^2 S^2
\tag{4.32}\]</span></span></p>
<div id="f1f61a46" class="cell" data-execution_count="21">
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a>S2 <span class="op">=</span> np.var(profits)</span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a>alpha <span class="op">=</span> <span class="fl">0.05</span></span>
<span id="cb27-3"><a href="#cb27-3" aria-hidden="true" tabindex="-1"></a>beta <span class="op">=</span> <span class="dv">1</span> <span class="op">-</span> <span class="fl">0.8</span></span>
<span id="cb27-4"><a href="#cb27-4" aria-hidden="true" tabindex="-1"></a>mde <span class="op">=</span> <span class="dv">50</span></span>
<span id="cb27-5"><a href="#cb27-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-6"><a href="#cb27-6" aria-hidden="true" tabindex="-1"></a>N <span class="op">=</span> ((norm().ppf(<span class="dv">1</span><span class="op">-</span>alpha) <span class="op">+</span> norm().ppf(<span class="dv">1</span> <span class="op">-</span> beta)) <span class="op">/</span> mde)<span class="op">**</span><span class="dv">2</span> <span class="op">*</span> S2</span>
<span id="cb27-7"><a href="#cb27-7" aria-hidden="true" tabindex="-1"></a>N <span class="op">=</span> <span class="bu">int</span>(N) <span class="op">+</span> <span class="dv">1</span></span>
<span id="cb27-8"><a href="#cb27-8" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Мінімальний розмір вибірки: </span><span class="sc">{</span>N<span class="sc">}</span><span class="ss">"</span>)</span></code><button title="Скопіювати в буфер обміну" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Мінімальний розмір вибірки: 2392</code></pre>
</div>
</div>
<p>Тепер ми знаємо, що нам потрібно 2392 користувачів, щоб перевірити нашу гіпотезу з MDE 50 грн.</p>
</section>
<section id="двовибірковий-t-тест" class="level2" data-number="4.10">
<h2 data-number="4.10" class="anchored" data-anchor-id="двовибірковий-t-тест"><span class="header-section-number">4.10</span> Двовибірковий <span class="math inline">\(t\)</span>-тест</h2>
<div id="exm-t-test2" class="theorem example">
<p><span class="theorem-title"><strong>Приклад 4.3</strong></span> &nbsp;</p>
<blockquote class="blockquote">
<p>На нашому онлайн-сервісі з розміщення оголошень є платні послуги просування. Ми плануємо запровадити знижки на ці послуги, щоб залучити більше користувачів і збільшити дохід. Для перевірки ефективності було вирішено провести A/B тест: одній половині нових користувачів ми не надавали знижки, а другій половині — надавали знижки на просування. Потрібно визначити, чи призвело це до зростання доходу.</p>
</blockquote>
</div>
<p>Для вирішення цього завдання ми не можемо використовувати одновибірковий <span class="math inline">\(t\)</span>-тест. Цього разу в нас дві вибірки <span class="math inline">\(A\)</span> — контроль, та <span class="math inline">\(B\)</span> — тест.</p>
<p>Наша гіпотеза звучить так:</p>
<p><span class="math display">\[
H_0: E A = E B \; проти \; H_1: E A &lt; E B
\]</span></p>
<p>Далі в нас може бути кілька варіантів:</p>
<ol type="1">
<li><strong>Обидві вибірки нормальні</strong>.</li>
</ol>
<p>Тоді у випадку рівних дисперсій <span class="math inline">\(\sigma^2_A = \sigma^2_B\)</span>, спільна дисперсія <span class="math inline">\(S^2_{pooled}\)</span> обчислюється за формулою:</p>
<p><span id="eq-t-test-full"><span class="math display">\[
S^2_{pooled} = \dfrac{(N - 1)S^2_A + (M - 1)S^2_B}{N + M - 2},
\tag{4.33}\]</span></span> де <span class="math inline">\(N\)</span>, <span class="math inline">\(M\)</span> — розмір контролю і тесту відповідно.</p>
<p>А критерій має такий вигляд:</p>
<p><span id="eq-t-test-full2"><span class="math display">\[
t(A, B) = \dfrac{\overline A - \overline B}{S^2_{pooled}\sqrt{1/N + 1/M}} \overset{H_0}{\sim} t_{n + m - 2}
\tag{4.34}\]</span></span> де <span class="math inline">\(n + m - 2\)</span> — ступені свободи.</p>
<p>У випадку, якщо дисперсії не рівні <span class="math inline">\(\sigma^2_A \neq \sigma^2_B\)</span><a href="#fn5" class="footnote-ref" id="fnref5" role="doc-noteref"><sup>5</sup></a>, то:</p>
<p><span id="eq-t-test-full3"><span class="math display">\[
t(A, B) = \dfrac{\overline A - \overline B}{\sqrt{S^2_{A}/N + S^2_{B}/M}} \overset{H_0}{\sim} t_{v}
\tag{4.35}\]</span></span> де <span class="math inline">\(v\)</span> — ступені свободи, які обчислюються за формулою:</p>
<p><span id="eq-t-test-full4"><span class="math display">\[
v = \frac{\left(\frac{S^2_{A}}{N} + \frac{S^2_{B}}{M} \right)^2}{\left(\frac{(S^2_{A})^2}{N^2(N - 1)} + \frac{(S^2_{B})^2}{M^2(M-1)} \right)}
\tag{4.36}\]</span></span></p>
<ol start="2" type="1">
<li><strong>Хоча б одна вибірка не нормальна</strong>.</li>
</ol>
<p>Тоді ми можемо використовувати нормальну апроксимація при великій вибірці:</p>
<p><span id="eq-t-test-full5"><span class="math display">\[
t(A, B) = \dfrac{\overline A - \overline B}{\sqrt{S^2_{A}/N + S^2_{B}/M}} \overset{H_0}{\sim} \mathcal{N}(0, 1)
\tag{4.37}\]</span></span> де <span class="math inline">\(S^2_{A}\)</span>, <span class="math inline">\(S^2_{B}\)</span> — вибіркові дисперсії.</p>
<section id="двовибірковий-t-тест-у-python" class="level3" data-number="4.10.1">
<h3 data-number="4.10.1" class="anchored" data-anchor-id="двовибірковий-t-тест-у-python"><span class="header-section-number">4.10.1</span> Двовибірковий <span class="math inline">\(t\)</span>-тест у Python</h3>
<p>Для реалізації двовибіркового <span class="math inline">\(t\)</span>-тесту в Python ми можемо використовувати <code>ttest_ind</code><a href="#fn6" class="footnote-ref" id="fnref6" role="doc-noteref"><sup>6</sup></a> з бібліотеки <code>scipy.stats</code>.</p>
<p>Подивимось на приклад з двома вибірками, перша вибірка — з експоненційного розподілу, а друга — з нормального розподілу.</p>
<div id="68c73ec1" class="cell" data-execution_count="22">
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a>X <span class="op">=</span> expon(scale<span class="op">=</span><span class="dv">1100</span>).rvs(<span class="dv">1000</span>)</span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a>Y <span class="op">=</span> norm(loc<span class="op">=</span><span class="dv">980</span>, scale<span class="op">=</span><span class="dv">30</span>).rvs(<span class="dv">1000</span>)</span>
<span id="cb29-3"><a href="#cb29-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-4"><a href="#cb29-4" aria-hidden="true" tabindex="-1"></a>t_results <span class="op">=</span> ttest_ind(X, Y, equal_var<span class="op">=</span><span class="va">False</span>, alternative<span class="op">=</span><span class="st">'greater'</span>)</span>
<span id="cb29-5"><a href="#cb29-5" aria-hidden="true" tabindex="-1"></a>ci_t_results <span class="op">=</span> t_results.confidence_interval(confidence_level<span class="op">=</span><span class="fl">0.95</span>)</span>
<span id="cb29-6"><a href="#cb29-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-7"><a href="#cb29-7" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"t-статистика = </span><span class="sc">{</span>np<span class="sc">.</span><span class="bu">round</span>(t_results.statistic, <span class="dv">2</span>)<span class="sc">}</span><span class="ss">"</span>)</span>
<span id="cb29-8"><a href="#cb29-8" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"p-значення = </span><span class="sc">{</span>np<span class="sc">.</span><span class="bu">round</span>(t_results.pvalue, <span class="dv">5</span>)<span class="sc">}</span><span class="ss">"</span>)</span>
<span id="cb29-9"><a href="#cb29-9" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Довірчий інтервал = </span><span class="sc">{</span>np<span class="sc">.</span><span class="bu">round</span>(ci_t_results, <span class="dv">2</span>)<span class="sc">}</span><span class="ss">"</span>)</span></code><button title="Скопіювати в буфер обміну" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>t-статистика = 3.62
p-значення = 0.00015
Довірчий інтервал = [68.38   inf]</code></pre>
</div>
</div>
<div class="callout callout-style-default callout-warning callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Попередження
</div>
</div>
<div class="callout-body-container callout-body">
<p>При використанні <span class="math inline">\(t\)</span>-тесту, як одновибіркового, так і двовибіркового, важливо пам’ятати, що:</p>
<ul>
<li>Елементи вибірок мають бути незалежні.
<ul>
<li>Наприклад, ваша вибірка не може містити кілька замовлень одного користувача. Вони мають бути агреговані, інакше критерії будуть невалідні!</li>
</ul></li>
<li>У двовибірковому критерії <strong>вибірки тесту і контролю повинні бути незалежні!</strong>.
<ul>
<li>Інакше критерії так само будуть невалідними.</li>
</ul></li>
</ul>
</div>
</div>
</section>
</section>
<section id="контрольні-питання" class="level2" data-number="4.11">
<h2 data-number="4.11" class="anchored" data-anchor-id="контрольні-питання"><span class="header-section-number">4.11</span> Контрольні питання</h2>


<div id="refs" class="references csl-bib-body hanging-indent" data-entry-spacing="0" role="list" style="display: none">
<div id="ref-Basu1955" class="csl-entry" role="listitem">
Basu, D. 1955. <em>On Statistics Independent of a Complete Sufficient Statistic</em>. <em>Sankhya</em>. Vol. 15.
</div>
<div id="ref-Cochran1934" class="csl-entry" role="listitem">
Cochran, William G. 1934. <em>The Distribution of Quadratic Forms in a Normal System, with Applications to the Analysis of Covariance</em>. <em>Mathematical Proceedings of the Cambridge Philosophical Society</em>. Vol. 30. 3. Cambridge University Press. <a href="https://doi.org/10.1017/S0305004100016595">https://doi.org/10.1017/S0305004100016595</a>.
</div>
</div>
</section>
<section id="footnotes" class="footnotes footnotes-end-of-document" role="doc-endnotes">
<hr>
<ol>
<li id="fn1"><p>Розподіл <span class="math inline">\(\chi^2\)</span> — це розподіл суми квадратів <span class="math inline">\(k\)</span> незалежних нормальних випадкових величин з нульовим математичним сподіванням. Тобто, якщо <span class="math inline">\(X_1, X_2, \ldots, X_k \sim \mathcal{N}(0, 1)\)</span>, то <span class="math inline">\(Y = X_1^2 + X_2^2 + \ldots + X_k^2 \sim \chi^2_k\)</span>.<a href="#fnref1" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn2"><p>Доведення <span class="citation" data-cites="Cochran1934">Cochran (<a href="references.html#ref-Cochran1934" role="doc-biblioref">1934</a>)</span>.<a href="#fnref2" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn3"><p>Розподіл Стьюдента — це розподіл, який виникає при нормальному розподілі з невідомою дисперсією. Якщо <span class="math inline">\(X_1, X_2, \ldots, X_n \sim \mathcal{N}(\mu, \sigma^2)\)</span>, то <span class="math inline">\(t = \dfrac{\overline{X} - \mu}{S/\sqrt{n}} \sim t_{n-1}\)</span>, де <span class="math inline">\(\overline{X}\)</span> — вибіркове середнє, <span class="math inline">\(S\)</span> — вибіркова стандартна девіація.<a href="#fnref3" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn4"><p>Доведення <span class="citation" data-cites="Basu1955">Basu (<a href="references.html#ref-Basu1955" role="doc-biblioref">1955</a>)</span>.<a href="#fnref4" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn5"><p>Такий підхід називається <span class="math inline">\(t\)</span>-тестом Уелча.<a href="#fnref5" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn6"><p>Документація: <a href="https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.ttest_ind.htm" class="uri">https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.ttest_ind.htm</a><a href="#fnref6" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
</ol>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Скопійовано!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Скопійовано!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./z-test.html" class="pagination-link" aria-label="$Z$-критерій Фішера">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title"><span class="math inline">\(Z\)</span>-критерій Фішера</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./monte-carlo.html" class="pagination-link" aria-label="Монте-Карло в задачах статистики">
        <span class="nav-page-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Монте-Карло в задачах статистики</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
<p>Прикладний статистичний аналіз</p>
</div>   
    <div class="nav-footer-center">
      &nbsp;
    </div>
    <div class="nav-footer-right">
<p>Ця книга створена за допомогою <a href="https://quarto.org/">Quarto</a>.</p>
</div>
  </div>
</footer>




</body></html>